// Tarjimalar. Kalit — o'zbekcha (lotin) matn.
//  kr — o'zbekcha (kirill): faqat avtomatik o'girish noto'g'ri chiqadigan satrlar (qolgani lib/i18n.js → toCyr)
//  ru — ruscha
//  ruPatterns — ichida o'zgaruvchan qismi bo'lgan server xabarlari

export const DICT = {
  kr: {
    "«Qo'shish» / «Add»": "«Қўшиш» / «Add»",
    "Bu iOS versiyasida faqat Safari orqali o'rnatiladi — havolani Safari'da oching.": "Бу iOS версиясида фақат Safari орқали ўрнатилади — ҳаволани Safari'да очинг.",
    "Safari'da": "Safari'да",
    "Chrome'da": "Chrome'да",
    "Siz ilovani Telegram (yoki boshqa ilova) ichidagi brauzerda ochgansiz — u yerdan bosh ekranga qo'shib bo'lmaydi.": "Сиз иловани Telegram (ёки бошқа илова) ичидаги браузерда очгансиз — у ердан бош экранга қўшиб бўлмайди.",
    "Siz ilovani Telegram (yoki boshqa ilova) ichidagi brauzerda ochgansiz — u yerdan o'rnatib bo'lmaydi.": "Сиз иловани Telegram (ёки бошқа илова) ичидаги браузерда очгансиз — у ердан ўрнатиб бўлмайди.",
    "Bu brauzerdan bosh ekranga qo'shib bo'lmaydi — Safari kerak.": "Бу браузердан бош экранга қўшиб бўлмайди — Safari керак.",
    "«Brauzerda ochish» / «Open in Chrome»": "«Браузерда очиш» / «Open in Chrome»",
    "iPhone'da o'rnatish uchun sahifani Safari'da ochish kerak bo'lishi mumkin.": "iPhone'да ўрнатиш учун саҳифани Safari'да очиш керак бўлиши мумкин.",
    "Kompyuterda: Chrome yoki Edge manzil qatoridagi «O'rnatish» belgisini bosing.": "Компьютерда: Chrome ёки Edge манзил қаторидаги «Ўрнатиш» белгисини босинг.",
    "Safari pastidagi {more} tugmasini bosing": "Safari пастидаги {more} тугмасини босинг",
    "Safari pastidagi {share} tugmasini bosing (iPad'da — yuqorida)": "Safari пастидаги {share} тугмасини босинг (iPad'да — юқорида)",
    "Chrome manzil qatoridagi {share} tugmasini bosing": "Chrome манзил қаторидаги {share} тугмасини босинг",
    "Edge manzil qatoridagi {share} tugmasini bosing": "Edge манзил қаторидаги {share} тугмасини босинг",
    "Safari'da {share} → {add}": "Safari'да {share} → {add}",
    "Chrome'da {dots} → {install}": "Chrome'да {dots} → {install}",
    Excel: "Excel",
    Du: "Ду", Se: "Се", Ch: "Чо", Pa: "Па", Ju: "Жу", Sh: "Ша", Ya: "Як",
    Iyun: "Июн", Iyul: "Июл", Yanvar: "Январ", Fevral: "Феврал", Aprel: "Апрел",
    "Excel yuklab olish": "Excel юклаб олиш",
    "Hisobot CSV": "Ҳисобот CSV",
    "«На экран Домой» / «Add to Home Screen»": "«На экран Домой» / «Add to Home Screen»",
    "Qidirish: Ф5, лоток…": "Қидириш: Ф5, лоток…",
    "Ma'lumotlar bazasiga ulanib bo'lmadi — MONGODB_URI va Atlas Network Access (0.0.0.0/0) ni tekshiring":
      "Маълумотлар базасига уланиб бўлмади — MONGODB_URI ва Atlas Network Access (0.0.0.0/0) ни текширинг",
    "Foydalanuvchi yo'q. Birinchi kirish uchun serverda APP_PASSWORD ni o'rnating":
      "Фойдаланувчи йўқ. Биринчи кириш учун серверда APP_PASSWORD ни ўрнатинг",
    "Serverga ulanib bo'lmadi. Internet yoki NEXT_PUBLIC_API_URL ni tekshiring.":
      "Серверга уланиб бўлмади. Интернет ёки NEXT_PUBLIC_API_URL ни текширинг.",
    "Sana formati YYYY-MM-DD": "Сана формати YYYY-MM-DD",
    "from va to sanalarini YYYY-MM-DD formatida bering": "from ва to саналарини YYYY-MM-DD форматида беринг",
    // oylik reja (tasdiqlangan reja)
    "Excel'dan yuklash": "Excel'дан юклаш",
    "Excel'da «{c}» ustuni bor — reja keyingi oy uchun deb taxmin qilindi. Kerak bo'lsa oyni o'zgartiring.": "Excel'да «{c}» устуни бор — режа кейинги ой учун деб тахмин қилинди. Керак бўлса ойни ўзгартиринг.",
    "Excel'da {d}-kungacha ustun bor, tanlangan oyda esa {n} kun — ortiqcha kunlardagi {q} dona olinmaydi.": "Excel'да {d}-кунгача устун бор, танланган ойда эса {n} кун — ортиқча кунлардаги {q} дона олинмайди.",
    "Excel'dagi nomi": "Excel'даги номи",
    "Oylik reja: Excel'dan yoki qo'lda": "Ойлик режа: Excel'дан ёки қўлда",
    "Excel'dan yuklangan": "Excel'дан юкланган",
    "Bo'sh jadval: mahsulot, buyurtmachi va kunlarni o'zingiz kiritasiz. Excel'dan nusxalab qo'yish ham mumkin.": "Бўш жадвал: маҳсулот, буюртмачи ва кунларни ўзингиз киритасиз. Excel'дан нусхалаб қўйиш ҳам мумкин.",
    "Excel'da «Наименование» ustuni topilmadi — oylik reja shaklidagi faylni tanlang": "Excel'да «Наименование» устуни топилмади — ойлик режа шаклидаги файлни танланг",
    "Excel'da kunlar (1, 2, 3 …) ustunlari topilmadi": "Excel'да кунлар (1, 2, 3 …) устунлари топилмади",
    "Excel'da mahsulot qatorlari topilmadi": "Excel'да маҳсулот қаторлари топилмади",
  },

  ru: {
    // telefonga o'rnatish yo'riqnomasi
    "Safari pastidagi {more} tugmasini bosing": "Нажмите внизу Safari кнопку {more}",
    "{share} ni tanlang": "Выберите {share}",
    "Ro'yxatni pastga suring va {add} ni tanlang": "Пролистайте список вниз и выберите {add}",
    "«Veb-ilova sifatida ochish» yoqilgan bo'lsin, so'ng {ok} ni bosing": "Оставьте включённым «Открывать как веб-приложение» и нажмите {ok}",
    "Safari pastidagi {share} tugmasini bosing (iPad'da — yuqorida)": "Нажмите внизу Safari кнопку {share} (на iPad — вверху)",
    "O'ng yuqoridagi {ok} ni bosing": "Справа вверху нажмите {ok}",
    "«Qo'shish» / «Add»": "«Добавить» / «Add»",
    "Chrome manzil qatoridagi {share} tugmasini bosing": "Нажмите {share} в адресной строке Chrome",
    "Edge manzil qatoridagi {share} tugmasini bosing": "Нажмите {share} в адресной строке Edge",
    "{add} ni tanlang": "Выберите {add}",
    "{ok} ni bosing": "Нажмите {ok}",
    "Bu iOS versiyasida faqat Safari orqali o'rnatiladi — havolani Safari'da oching.": "На этой версии iOS установка только через Safari — откройте ссылку в Safari.",
    "Havolani nusxalang (pastdagi tugma)": "Скопируйте ссылку (кнопка ниже)",
    "{safari} ni oching va manzil qatoriga qo'ying": "Откройте {safari} и вставьте её в адресную строку",
    "Safari'da {share} → {add}": "В Safari: {share} → {add}",
    "Siz ilovani Telegram (yoki boshqa ilova) ichidagi brauzerda ochgansiz — u yerdan bosh ekranga qo'shib bo'lmaydi.": "Вы открыли сайт во встроенном браузере Telegram (или другого приложения) — оттуда нельзя добавить на главный экран.",
    "Bu brauzerdan bosh ekranga qo'shib bo'lmaydi — Safari kerak.": "Из этого браузера нельзя добавить на главный экран — нужен Safari.",
    "O'ng yuqoridagi {dots} menyusidan {open} ni tanlang": "Справа вверху в меню {dots} выберите {open}",
    "«Brauzerda ochish» / «Open in Chrome»": "«Открыть в браузере» / «Open in Chrome»",
    "Chrome'da {dots} → {install}": "В Chrome: {dots} → {install}",
    "«Ilovani o'rnatish» / «Установить приложение»": "«Установить приложение»",
    "Siz ilovani Telegram (yoki boshqa ilova) ichidagi brauzerda ochgansiz — u yerdan o'rnatib bo'lmaydi.": "Вы открыли сайт во встроенном браузере Telegram (или другого приложения) — оттуда установить нельзя.",
    "Pastdagi {burger} menyusini oching": "Внизу откройте меню {burger}",
    "{samsung} ni tanlang": "Выберите {samsung}",
    "O'ng yuqoridagi {dots} menyusini oching": "Справа вверху откройте меню {dots}",
    "{install} ni tanlang (yoki «Bosh ekranga qo'shish»)": "Выберите {install} (или «Добавить на главный экран»)",
    "Telefonga o'rnatish": "Установить на телефон",
    "Havolani nusxalang": "Скопируйте ссылку",
    "Pastdagi tugma orqali «Bosh ekranga qo'shish» — qanday qilishni ko'rsatamiz.": "Через «Добавить на экран Домой» — покажем, как это сделать.",
    "iPhone'da o'rnatish uchun sahifani Safari'da ochish kerak bo'lishi mumkin.": "Для установки на iPhone может понадобиться открыть страницу в Safari.",
    "Kompyuterda: Chrome yoki Edge manzil qatoridagi «O'rnatish» belgisini bosing.": "На компьютере: нажмите значок «Установить» в адресной строке Chrome или Edge.",
    "Nusxalandi ✓": "Скопировано ✓",
    "Havolani nusxalash": "Скопировать ссылку",
    "Qanday?": "Как?",
    // tayyor mahsulot: marka tuzatish
    "Markani tuzatish": "Исправить марку",
    "Boshqa markaga o'tkazish": "Перенести на другую марку",
    "Marka tuzatishlari": "Исправления марок",
    "Tuzatishni bekor qilasizmi?": "Отменить исправление?",
    "Noto'g'ri yozilgan marka (qayerdan)": "Ошибочная марка (откуда)",
    "To'g'ri marka (qayerga)": "Правильная марка (куда)",
    "Ikkala markani tanlang": "Выберите обе марки",
    "Tuzatildi: {a} → {b}, {n} dona": "Исправлено: {a} → {b}, {n} шт",
    "tuzatish {n}": "исправление {n}",
    "Tuzatish": "Исправить",
    "Masalan: 02.10 kunlik hisobotda adashib yozilgan": "Например: ошибочно внесено в отчёт за 02.10",
    "Kunlik hisobotga mahsulot boshqa marka bilan yozib yuborilgan bo'lsa — noto'g'ri markadan ayirib, to'g'risiga o'tkazing. Jami tayyor mahsulot soni o'zgarmaydi, o'zgarish tarixda saqlanadi.": "Если в ежедневный отчёт изделие внесено под другой маркой — спишите с ошибочной и перенесите на правильную. Общее количество готовой продукции не меняется, изменение сохраняется в истории.",
    "To'g'ri mahsulotni tanlang (boshqa marka bo'lishi kerak)": "Выберите правильное изделие (другая марка)",
    "Markani tuzatishni faqat ПТО, administrator yoki rahbar qila oladi": "Исправлять марку могут только ПТО, администратор или руководитель",
    "Markani tuzatishni faqat ПТО, administrator yoki rahbar bekor qila oladi": "Отменить исправление марки могут только ПТО, администратор или руководитель",
    "Qoldiq = boshlang'ich + sifatli fakt − jo'natilgan − brakka chiqarilgan ± marka tuzatishlari. «Band» — faol buyurtmalarning jo'natilmagan qismi. Qiymat kalkulyatsiyadagi tannarx (marja va QQSsiz) bo'yicha.": "Остаток = начальный + годный факт − отгружено − списано в брак ± исправления марок. «Занято» — неотгруженная часть активных заказов. Стоимость — по себестоимости из калькуляции (без маржи и НДС).",
    "Omborda yetarli emas. Qoldiq: {n} dona": "Недостаточно на складе. Остаток: {n} шт",
    // buyurtmalar rejasi: hamma / tanlangan buyurtmalar
    "yan": "янв",
    "fev": "фев",
    "mar": "мар",
    "apr": "апр",
    "may": "мая",
    "iyun": "июн",
    "iyul": "июл",
    "avg": "авг",
    "sen": "сен",
    "okt": "окт",
    "noy": "ноя",
    "dek": "дек",
    "bugun": "сегодня",
    "Dam olish": "Выходной",
    "Reja yo'q": "Нет плана",
    "Har katakda: mahsulot va soni (dona), tagida — qaysi buyurtmalar uchun. Pastki satr — kun bo'yicha jami va beton hajmi (qizil — kunlik beton cheklovidan oshgan).": "В каждой ячейке: изделие и количество (шт), ниже — для каких заказов. Нижняя строка — итог за день и объём бетона (красным — превышен дневной лимит бетона).",
    "to'liq jo'natildi": "отгружено полностью",
    "Yig'ish": "Свернуть",
    "Yana {n} ta mahsulot": "Ещё {n} изделий",
    "{n} xil mahsulot": "{n} наименований",
    "{n} tasi to'liq jo'natilgan": "{n} отгружено полностью",
    "Tizimdan oldin jo'natilgan: {n}": "Отгружено до запуска системы: {n}",
    "Kunlik ishlab chiqarish rejasi": "План производства по дням",
    "Kunlik reja (PDF)": "План по дням (PDF)",
    "PDF ni ulashish": "Поделиться PDF",
    "PDF: nechta ish kuni": "PDF: сколько рабочих дней",
    "{n} kun": "{n} дн.",
    "faqat shular rejalashtirilgan": "запланированы только они",
    "Tayyorlandi: {d}": "Сформировано: {d}",
    "Tuzdi (ПТО)": "Составил (ПТО)",
    "Tasdiqlayman": "Утверждаю",
    "Soni, dona": "Кол-во, шт",
    "Buyurtmalar": "Заказы",
    "Yakshanba": "Воскресенье",
    "Dushanba": "Понедельник",
    "Seshanba": "Вторник",
    "Chorshanba": "Среда",
    "Payshanba": "Четверг",
    "Juma": "Пятница",
    "Shanba": "Суббота",
    "PDF tayyorlab bo'lmadi": "Не удалось сформировать PDF",
    "jami": "всего",
    "Qaysi buyurtmalar": "Какие заказы",
    "Hamma buyurtmalar": "Все заказы",
    "Kerakli buyurtmalar": "Выбранные заказы",
    "Tanlangan buyurtmalar": "Выбранные заказы",
    "Qidirish: buyurtmachi, shartnoma, №": "Поиск: заказчик, договор, №",
    "Faqat shularni rejalashtirish (boshqa buyurtmalarni hisobga olmasdan)": "Планировать только их (без учёта других заказов)",
    "Rejasini ko'rmoqchi bo'lgan buyurtmalarni belgilang.": "Отметьте заказы, план которых нужно показать.",
    "Faqat tanlangan buyurtmalar rejalashtirildi — boshqa buyurtmalar qoliplarni band qilmaydi deb hisoblandi (shularga ustuvorlik bersak nima bo'ladi).": "Запланированы только выбранные заказы — считается, что остальные заказы не занимают формы (что будет, если дать им приоритет).",
    "Reja hamma buyurtmalar bilan birga hisoblandi (navbat va quvvat umumiy) — ekranda faqat tanlanganlari ko'rsatilgan.": "План рассчитан вместе со всеми заказами (общая очередь и мощность) — на экране показаны только выбранные.",
    "Tanlangan buyurtmalarda ishlab chiqarish kerak bo'lgan mahsulot yo'q.": "В выбранных заказах нет изделий, которые нужно производить.",
    "Buyurtma tanlanmagan.": "Заказ не выбран.",
    "hamma buyurtmalar": "все заказы",
    // ombor: yangi material / xo'jalik moli
    "Texnika va jihozlar": "Техника и оборудование",
    "Asbob-uskunalar": "Инструменты",
    "Xo'jalik mollari": "Хозтовары",
    "Maxsus kiyim va himoya": "Спецодежда и СИЗ",
    "Elektr mollari": "Электротовары",
    "Yangi material / mol": "Новый материал / товар",
    "Yangi material / mol qo'shish": "Добавить новый материал / товар",
    "«{q}» — yangi material qo'shish": "«{q}» — добавить новый материал",
    "ro'yxatda yo'q bo'lsa": "если нет в списке",
    "Bunday material bor:": "Такой материал уже есть:",
    "O'xshash materiallar bor:": "Есть похожие материалы:",
    "arxivda": "в архиве",
    "Bu nomdagi material allaqachon bor — yangisini qo'shmang, o'shani tanlang": "Материал с таким названием уже есть — выберите его, не добавляйте новый",
    "Bu nomdagi material allaqachon bor": "Материал с таким названием уже есть",
    "Bu nomdagi material arxivda bor — «Materiallar» bo'limida arxivdan chiqaring": "Материал с таким названием есть в архиве — верните его из архива в разделе «Материалы»",
    "Narx kirimda yoziladi (har xariddagi narx). Material narxini ПТО belgilaydi.": "Цена указывается при приходе (цена каждой закупки). Цену материала устанавливает ПТО.",
    // kalkulyatsiya: tijorat taklifi (Word)
    "Tijorat taklifi (Word)": "Коммерческое предложение (Word)",
    "Tijorat taklifi (katalog)": "Коммерческое предложение (каталог)",
    "Mahsulotlarni belgilang — Word faylda 1 dona narxi QQSsiz (kalkulyatsiyadan) chiqadi. Narx yoki nomni shu yerda o'zgartirish mumkin, katalogga ta'sir qilmaydi.": "Отметьте изделия — в файле Word будет цена за 1 шт без НДС (из калькуляции). Цену или название можно изменить здесь, на каталог это не влияет.",
    "Chiquvchi №": "Исх. №",
    "Kimga": "Кому",
    "Matn": "Текст",
    "Narx ustuni sarlavhasi": "Заголовок столбца цены",
    "Tanlangan: {n} ta": "Выбрано: {n}",
    "Hammasini belgilash": "Выбрать все",
    "Tozalash": "Очистить",
    "Hujjatdagi nomi": "Название в документе",
    "Narx QQSsiz, so'm": "Цена без НДС, сум",
    "Guruhni belgilash": "Выбрать группу",
    "Guruhsiz": "Без группы",
    "Narxi yo'q: {list} — kalkulyatsiya kiritilmagan, narxni qo'lda yozing.": "Нет цены: {list} — калькуляция не заполнена, укажите цену вручную.",
    "Narxi yo'q mahsulotlar: {list} — kalkulyatsiyani kiriting yoki narxni qo'lda yozing": "Изделия без цены: {list} — заполните калькуляцию или укажите цену вручную",
    "Kamida bitta mahsulot tanlang": "Выберите хотя бы одно изделие",
    "Word fayl tayyor": "Файл Word готов",
    "Tijorat taklifi shablonini yuklab bo'lmadi": "Не удалось загрузить шаблон коммерческого предложения",
    // buyurtmalar: ko'p mahsulotli buyurtma, tizimdan oldin jo'natilgan
    "Shartnoma (договор) №": "Номер договора",
    "Shartnoma № {n}": "Договор № {n}",
    "Shartnoma №": "Договор №",
    "Qidirish: buyurtmachi, shartnoma, mahsulot": "Поиск: заказчик, договор, изделие",
    "Qidirish: buyurtmachi, №, mahsulot": "Поиск: заказчик, №, изделие",
    "qabul {d}": "принят {d}",
    "Tizimdan oldin jo'natilgan": "Отгружено до запуска системы",
    "oldin {n}": "ранее {n}",
    "qoldi {n}": "осталось {n}",
    "Tizim ishga tushishidan oldin olingan buyurtma — bir qismi allaqachon jo'natilgan": "Заказ принят до запуска системы — часть уже отгружена",
    "Oldin jo'natilgan": "Отгружено ранее",
    "Kunlik hisobotdan": "По ежедневному отчёту",
    "Kamida bitta mahsulot qo'shing": "Добавьте хотя бы одно изделие",
    "Oldin jo'natilgan soni buyurtma sonidan ko'p bo'lmaydi": "Отгружено ранее не может быть больше количества в заказе",
    "Mahsulotlar ro'yxati noto'g'ri": "Неверный список изделий",
    "Narx manfiy bo'lmaydi": "Цена не может быть отрицательной",
    "Oldin jo'natilgan soni manfiy bo'lmaydi": "Отгружено ранее не может быть отрицательным",
    "Bir mahsulot buyurtmada ikki marta bo'lmasin — sonini bitta qatorga yozing": "Одно изделие не может быть в заказе дважды — укажите количество одной строкой",
    "Olib tashlanayotgan mahsulot kunlik hisobotda shu buyurtma bo'yicha jo'natilgan — avval o'sha jo'natishni boshqa buyurtmaga bog'lang": "Удаляемое изделие уже отгружалось по этому заказу в ежедневном отчёте — сначала привяжите эту отгрузку к другому заказу",
    "Bitta buyurtmada bir nechta mahsulot bo'lishi mumkin. «Jo'natildi» = tizimdan oldin jo'natilgan (buyurtmada qo'lda kiritiladi) + kunlik hisobotda shu buyurtmaga bog'langan jo'natishlar. Narx 0 bo'lsa, kalkulyatsiyadagi QQS bilan narx olinadi.": "В одном заказе может быть несколько изделий. «Отгружено» = отгружено до запуска системы (вводится в заказе вручную) + отгрузки в ежедневном отчёте, привязанные к заказу. Если цена 0, берётся цена с НДС из калькуляции.",
    "«Oldin jo'natilgan» — tizimdan oldin jo'natib bo'lingan soni. U ombor qoldig'iga ta'sir qilmaydi (boshlang'ich qoldiqda allaqachon hisobga olingan), faqat buyurtmaning qolgan qismini kamaytiradi.": "«Отгружено ранее» — количество, отгруженное до запуска системы. На складской остаток не влияет (уже учтено в начальном остатке), только уменьшает остаток по заказу.",
    "Narx bo'sh bo'lsa, kalkulyatsiyadagi QQS bilan narx olinadi. Jo'natishlar kunlik hisobotda shu buyurtmaga bog'lanadi.": "Если цена не указана, берётся цена с НДС из калькуляции. Отгрузки привязываются к заказу в ежедневном отчёте.",
    // buxgalteriya: material hisoboti
    "Material, 1 dona": "Материалы, 1 шт",
    "Material, jami": "Материалы, всего",
    "Narx QQSsiz, 1 dona": "Цена без НДС, 1 шт",
    "Ish haqi va boshq.": "Зарплата и проч.",
    "1 dona narxi (QQSsiz)": "Цена за 1 шт (без НДС)",
    "Ish haqi va boshqa xarajatlar, so'm": "Зарплата и прочие расходы, сум",
    "Har bir mahsulot: (1 dona QQSsiz narx − 1 dona material xarajati) × soni. Hammasining yig'indisi.": "По каждому изделию: (цена за 1 шт без НДС − материальные затраты на 1 шт) × кол-во. Итог — сумма по всем.",
    "Jadval kunlik hisobotdagi faktdan (dona), beton hajmi mahsulot normasidan, 1 dona material xarajati va QQSsiz narxi esa kalkulyatsiyadan olinadi. Istalgan katakni tuzatib, «Word (DOCX) yuklab olish»ni bosing — fayl asl shakldagidek chiqadi.": "Количество — из факта ежедневного отчёта, объём бетона — из нормы изделия, материальные затраты и цена без НДС на 1 шт — из калькуляции. Исправьте любую ячейку и нажмите «Скачать Word (DOCX)» — файл выйдет в исходном виде.",
    "Material hisoboti": "Отчёт по материалам",
    "Oyda quyilgan mahsulotlar ro'yxati — Word (DOCX) shaklida": "Список изделий, залитых за месяц, — в формате Word (DOCX)",
    "Buxgalter (material hisoboti)": "Бухгалтер (отчёт по материалам)",
    "Buxgalter": "Бухгалтер",
    "Hisobot": "Отчёт",
    "Tannarx": "Себест.",
    "hali saqlanmagan": "ещё не сохранён",
    "saqlangan": "сохранён",
    "o'zgartirildi": "изменён",
    "Word (DOCX) yuklab olish": "Скачать Word (DOCX)",
    "Jadval kunlik hisobotdagi faktdan (dona), beton hajmi mahsulot normasidan, 1 dona material xarajati esa kalkulyatsiyadan olinadi. Istalgan katakni tuzatib, «Word (DOCX) yuklab olish»ni bosing — fayl asl shakldagidek chiqadi.": "Количество берётся из факта ежедневного отчёта, объём бетона — из нормы изделия, материальные затраты на 1 шт — из калькуляции. Исправьте любую ячейку и нажмите «Скачать Word (DOCX)» — файл выйдет в исходном виде.",
    "Saqlangan hisobot kunlik hisobotdagi sonlardan farq qiladi (kunlik hisobot keyin o'zgartirilgan bo'lishi mumkin).": "Сохранённый отчёт отличается от ежедневных отчётов (возможно, их изменили позже).",
    "Qaytadan to'ldirish": "Заполнить заново",
    "Hujjat sanasi": "Дата документа",
    "Direktor": "Директор",
    "Sex boshlig'i": "Начальник цеха",
    "Moddiy hisobchi": "Материальный бухгалтер",
    "Brakni ham qo'shish": "Учитывать брак",
    "Kunlik hisobotdan qayta to'ldirish": "Заполнить из ежедневных отчётов",
    "Bu oyda kunlik hisobotda ishlab chiqarish yo'q. Qatorlarni qo'lda qo'shishingiz mumkin.": "В этом месяце в ежедневных отчётах нет выпуска. Строки можно добавить вручную.",
    "Mahsulot nomi": "Наименование изделия",
    "Soni": "Кол-во",
    "1 dona material xarajati": "Материальные затраты на 1 шт",
    "Jami material xarajat, so'm": "Всего материальных затрат, сум",
    "Yuqoriga": "Вверх",
    "Pastga": "Вниз",
    "— bo'sh qator —": "— пустая строка —",
    "Qator qo'shish": "Добавить строку",
    "Jadval kunlik hisobot va kalkulyatsiyadan qaytadan to'ldiriladi. Qo'lda kiritilgan o'zgarishlar yo'qoladi. Davom etasizmi?": "Таблица будет заново заполнена из ежедневных отчётов и калькуляции. Ручные изменения пропадут. Продолжить?",
    "Saqlanmagan o'zgarishlar bor. Ularni tashlab ketasizmi?": "Есть несохранённые изменения. Отменить их?",
    "Jadvalda qator yo'q": "В таблице нет строк",
    "Mahsulot nomi kiritilmagan qator bor": "Есть строка без наименования изделия",
    "Faylni tayyorlab bo'lmadi": "Не удалось подготовить файл",
    "Hisobot shablonini yuklab bo'lmadi": "Не удалось загрузить шаблон отчёта",
    "Shablon buzilgan: mahsulot qatori topilmadi": "Шаблон повреждён: не найдена строка изделия",
    "Qatorlar ro'yxati noto'g'ri": "Неверный список строк",
    "Oy formati YYYY-MM": "Формат месяца ГГГГ-ММ",
    /* ---------- karkas, menyu, kirish ---------- */
    "Kunlik hisobot": "Ежедневный отчёт",
    "Reja / fakt, xomashyo sarfi, jo'natish": "План / факт, расход сырья, отгрузка",
    "Oylik hisobot": "Месячный отчёт",
    "Reja bajarilishi, haqiqiy sarf va norma farqi": "Выполнение плана, фактический расход и отклонение от нормы",
    Ombor: "Склад",
    "Materiallar qoldig'i, kirim va chiqim": "Остатки материалов, приход и расход",
    "Kirim-chiqim tarixi": "История прихода и расхода",
    "Ombordagi barcha harakatlar": "Все движения по складу",
    "Qoldiq va ehtiyoj": "Остатки и потребность",
    "Material va tayyor mahsulot qiymati, buyurtmalar uchun ehtiyoj": "Стоимость материалов и готовой продукции, потребность под заказы",
    Buyurtmalar: "Заказы",
    "Buyurtmachilar, muddatlar va jo'natish holati": "Заказчики, сроки и статус отгрузки",
    Kalkulyatsiya: "Калькуляция",
    "Tannarx va sotuv narxi — Excel tartibida": "Себестоимость и цена продажи — как в Excel",
    Katalog: "Каталог",
    "Mahsulotlar, sarf normalari va kalkulyatsiya kartalari": "Изделия, нормы расхода и калькуляционные карты",
    Materiallar: "Материалы",
    "Narxlar, beton retseptlari va sozlamalar": "Цены, рецепты бетона и настройки",
    "Sex va texnika": "Цеха и техника",
    "Chiqim manzillari: bo'limlar va mashinalar": "Куда идёт расход: подразделения и машины",
    Boshqaruv: "Управление",
    "Foydalanuvchilar, zaxira nusxa va o'zgarishlar tarixi": "Пользователи, резервная копия и история изменений",
    Kunlik: "День",
    Oylik: "Месяц",
    Tarix: "История",
    "Sex/texnika": "Цеха/техника",
    Qoldiq: "Остаток",
    Buyurtma: "Заказ",
    "Zavod ish stoli": "Рабочий стол завода",
    "Davom etish uchun login va parolni kiriting": "Введите логин и пароль, чтобы продолжить",
    Login: "Логин",
    Parol: "Пароль",
    "Tekshirilmoqda…": "Проверка…",
    Kirish: "Войти",
    "Kunlik hisobotda saqlanmagan o'zgarishlar bor. Ularni tashlab ketasizmi?": "В ежедневном отчёте есть несохранённые изменения. Отменить их?",
    "Bo'limlar": "Разделы",
    "Temir-beton zavodi": "Завод ЖБИ",
    "Menyuni yopish": "Закрыть меню",
    "Server bilan ulangan": "Связь с сервером есть",
    "Ulanishda xato": "Ошибка связи",
    "Yuklanmoqda…": "Загрузка…",
    Chiqish: "Выйти",
    Kirim: "Приход",
    Chiqim: "Расход",
    "Qayta urinish": "Повторить",
    "Ma'lumotlar yuklanmoqda…": "Загрузка данных…",
    "Davom etish uchun yangi parol o'rnating.": "Чтобы продолжить, установите новый пароль.",
    "Ma'lumotlarni yuklab bo'lmadi.": "Не удалось загрузить данные.",
    "Asosiy bo'limlar": "Основные разделы",
    "Kirim yoki chiqim": "Приход или расход",
    Menyu: "Меню",
    "Parol o'zgartirildi": "Пароль изменён",
    "Serverga ulanib bo'lmadi. Internet yoki NEXT_PUBLIC_API_URL ni tekshiring.": "Нет связи с сервером. Проверьте интернет или NEXT_PUBLIC_API_URL.",
    "Serverga ulanib bo'lmadi": "Нет связи с сервером",
    "Kirishda xatolik": "Ошибка входа",

    /* ---------- rollar ---------- */
    Administrator: "Администратор",
    "ПТО muhandisi": "Инженер ПТО",
    Omborchi: "Кладовщик",
    Rahbar: "Руководитель",
    Kurator: "Куратор",
    "Rahbar (faqat ko'rish)": "Руководитель (только просмотр)",
    "Kurator (faqat ko'rish)": "Куратор (только просмотр)",

    /* ---------- umumiy ---------- */
    Saqlash: "Сохранить",
    "Saqlanmoqda…": "Сохранение…",
    Saqlandi: "Сохранено",
    "Bekor qilish": "Отмена",
    Yopish: "Закрыть",
    "O'chirish": "Удалить",
    "O'chirildi": "Удалено",
    Tasdiqlash: "Подтвердить",
    Tahrirlash: "Изменить",
    Qidirish: "Поиск",
    "Qidirish…": "Поиск…",
    "Hech narsa topilmadi": "Ничего не найдено",
    Barchasi: "Все",
    Hammasi: "Все",
    Bugun: "Сегодня",
    Sana: "Дата",
    Izoh: "Примечание",
    Nomi: "Название",
    Birlik: "Ед.",
    Narx: "Цена",
    Narxi: "Цена",
    Summa: "Сумма",
    "Summa, so'm": "Сумма, сум",
    "so'm": "сум",
    "mln so'm": "млн сум",
    dona: "шт",
    Jami: "Итого",
    Material: "Материал",
    Mahsulot: "Изделие",
    Mahsulotlar: "Изделия",
    Soni: "Кол-во",
    Miqdor: "Количество",
    Guruh: "Группа",
    Holat: "Статус",
    Turi: "Тип",
    Qiymat: "Значение",
    "Chop etish": "Печать",
    Ulashish: "Поделиться",
    Yangi: "Новый",
    "Yuklab olish": "Скачать",
    "Tayyorlanmoqda…": "Подготовка…",
    "O'zgartirish": "Изменить",
    "— o'chirilgan —": "— удалено —",
    "o'chirilgan": "удалено",
    "Excel faylni tayyorlab bo'lmadi": "Не удалось подготовить файл Excel",
    "Fayl yuklab olindi": "Файл скачан",
    "Bu qurilmada ulashish yo'q — fayl yuklab olindi": "На этом устройстве нельзя поделиться — файл скачан",
    Saqlanmadi: "Не сохранено",
    ha: "да",
    "yo'q": "нет",
    "{n} ta": "{n} шт",
    Yozuvlar: "Записи",
    Dan: "С",
    Gacha: "По",

    /* ---------- guruhlar, holatlar, qator turlari ---------- */
    Beton: "Бетон",
    Xomashyo: "Сырьё",
    Metall: "Металл",
    "Zakladnoy detallar": "Закладные детали",
    "Yoqilg'i va moylar": "Топливо и масла",
    "Ehtiyot qismlar": "Запчасти",
    Boshqa: "Прочее",
    "Xizmat / energiya": "Услуги / энергия",
    Faol: "Активные",
    Jarayonda: "В работе",
    Tayyor: "Готов",
    Topshirildi: "Сдан",
    "so'm × m³ beton": "сум × м³ бетона",
    "so'm × kg metall": "сум × кг металла",
    "% oldingi qatordan": "% от предыдущей строки",
    "% ishlab chiqarish tannarxidan": "% от производственной себестоимости",
    "so'm (qat'iy)": "сум (фиксированно)",

    /* ---------- ombor (omborchi) ---------- */
    "Ombor qiymati": "Стоимость склада",
    "Kam qoldi / tugagan": "Мало / закончилось",
    "Material qidirish…": "Поиск материала…",
    "Yangi material": "Новый материал",
    "Kam qoldi": "Мало",
    Tugagan: "Нет в наличии",
    "Material yo'q": "Материалов нет",
    min: "мин",
    "Oxirgi harakatlar": "Последние движения",
    "Bu material bo'yicha hali kirim-chiqim yo'q": "По этому материалу ещё не было движений",
    "Material qo'shildi": "Материал добавлен",
    "Minimal qoldiq": "Минимальный остаток",
    "Kod / artikul": "Код / артикул",
    "Materialni tanlang": "Выберите материал",
    "Miqdorni to'g'ri kiriting": "Введите правильное количество",
    "Qayerga ketganini kiriting: bo'lim, texnika yoki mas'ul shaxs": "Укажите, куда выдано: подразделение, техника или ответственный",
    "Kirim saqlandi": "Приход сохранён",
    "Chiqim saqlandi": "Расход сохранён",
    "Keyin qoladi": "Останется",
    "omborda yetarli emas": "на складе недостаточно",
    "Birlik narxi": "Цена за ед.",
    "Nakladnoy raqami": "Номер накладной",
    Nakladnoy: "Накладная",
    "Yetkazib beruvchi": "Поставщик",
    "Kim qabul qildi": "Кто принял",
    "Bo'lim / sex": "Подразделение / цех",
    Texnika: "Техника",
    "Kim oldi (mas'ul shaxs)": "Кто получил (ответственный)",
    "Kirimni saqlash": "Сохранить приход",
    "Chiqimni saqlash": "Сохранить расход",
    "7 kun": "7 дней",
    "30 kun": "30 дней",
    "Shu oy": "Этот месяц",
    Davr: "Период",
    "Bu yozuv bekor qilinsinmi? Qoldiq qayta hisoblanadi.": "Отменить эту запись? Остаток будет пересчитан.",
    "Bekor qilindi": "Отменено",
    "Qayerdan / qayerga": "Откуда / куда",
    "Mas'ul shaxs": "Ответственный",
    "Kim kiritdi": "Кто внёс",
    "Kirim va chiqim": "Приход и расход",
    "Faqat kirim": "Только приход",
    "Faqat chiqim": "Только расход",
    "Barcha materiallar": "Все материалы",
    "Bo'lim / texnika": "Подразделение / техника",
    "Barcha bo'lim va texnikalar": "Все подразделения и техника",
    "Kirim summasi": "Сумма прихода",
    "Chiqim summasi": "Сумма расхода",
    "Bu davrda kirim-chiqim yo'q": "За этот период движений нет",
    "Faqat oxirgi 1000 ta yozuv ko'rsatildi — davrni qisqartiring.": "Показаны только последние 1000 записей — сократите период.",
    jami: "итого",
    "Bo'limlar va sexlar": "Подразделения и цеха",
    "Masalan: Beton sexi, Armatura sexi, Oshxona": "Например: Бетонный цех, Арматурный цех, Столовая",
    "Texnika va mashinalar": "Техника и машины",
    "Masalan: KAMAZ, Avtokran, Yuklagich": "Например: КАМАЗ, Автокран, Погрузчик",
    "«{name}» o'chirilsinmi? Tarixda ishlatilgan bo'lsa, arxivga o'tkaziladi.": "Удалить «{name}»? Если есть в истории — будет перенесено в архив.",
    "Arxivga o'tkazildi": "Перенесено в архив",
    "Chiqim qilinganda material qayerga ketganini shu ro'yxatlardan tanlaysiz.": "При расходе место назначения выбирается из этих списков.",
    "Qo'shish": "Добавить",
    "Davlat raqami": "Гос. номер",
    Kodi: "Код",
    "Hali qo'shilmagan": "Пока ничего не добавлено",
    "(arxivda)": "(в архиве)",
    Qaytarish: "Вернуть",
    "Arxivdagilarni ko'rsatish": "Показать архивные",

    /* ---------- kunlik hisobot ---------- */
    "Saqlanmagan o'zgarishlar bor. Ularni tashlab, boshqa kunga o'tasizmi?": "Есть несохранённые изменения. Перейти на другой день без сохранения?",
    "Sarf normadan to'ldirildi — tekshirib, saqlang": "Расход заполнен по норме — проверьте и сохраните",
    "{d} saqlandi": "{d} сохранено",
    "Bu sana boshlang'ich qoldiqdan oldin — qoldiqlar noma'lum, fayl tayyorlanmaydi": "Дата раньше начального остатка — остатки неизвестны, файл не формируется",
    "Diqqat: fayl saqlanmagan o'zgarishlar bilan tayyorlandi": "Внимание: файл сформирован с несохранёнными изменениями",
    "{d} kunidagi barcha yozuvlar o'chirilsinmi?": "Удалить все записи за {d}?",
    "Oldingi kun": "Предыдущий день",
    "Keyingi kun": "Следующий день",
    Saqlanmagan: "Не сохранено",
    Saqlangan: "Сохранено",
    "Excel yuklab olish": "Скачать Excel",
    "Kunni o'chirish": "Удалить день",
    "Bu sana boshlang'ich qoldiq sanasidan ({d}) oldin — qoldiqlar hisoblanmaydi.": "Эта дата раньше даты начального остатка ({d}) — остатки не считаются.",
    "Mahsulotlar: reja / fakt": "Изделия: план / факт",
    "Reja, dona": "План, шт",
    "Fakt, dona": "Факт, шт",
    Bajarilishi: "Выполнение",
    "— mahsulot tanlang —": "— выберите изделие —",
    Reja: "План",
    Fakt: "Факт",
    reja: "план",
    fakt: "факт",
    "Qatorni o'chirish": "Удалить строку",
    "+ Mahsulot qo'shish": "+ Добавить изделие",
    "Xomashyo va materiallar": "Сырьё и материалы",
    "Sarfni normadan to'ldirish": "Заполнить расход по норме",
    "Kun boshida": "На начало дня",
    "Kerak (reja)": "Нужно (план)",
    "Norma (fakt)": "Норма (факт)",
    Sarf: "Расход (пр-во)",
    "Harakat yo'q. «Barcha materiallar»ni yoqing.": "Движений нет. Включите «Все материалы».",
    "Normadan farq: {p} %": "Отклонение от нормы: {p} %",
    "Metall kg da. «Norma (fakt)» — fakt × Норма (beton → qum/sement/sheben, elektrod = metallning {p} %). Sarf normadan 10 % dan ko'p farq qilsa sariq bilan belgilanadi. Kirim va chiqim — omborchi kiritgan harakatlar («Ombor» bo'limi).":
      "Металл в кг. «Норма (факт)» — факт × Норма (бетон → песок/цемент/щебень, электрод = {p} % от металла). Отклонение расхода от нормы более 10 % выделяется жёлтым. Приход и расход — движения, внесённые кладовщиком (раздел «Склад»).",
    "Tayyor mahsulot qoldig'i": "Остаток готовой продукции",
    "Qoldiq yo'q.": "Остатков нет.",
    Boshida: "На начало",
    Ishlandi: "Изготовлено",
    "Jo'natildi": "Отгружено",
    "Jo'natish (отгрузка)": "Отгрузка",
    Qayerga: "Куда",
    Mashina: "Машина",
    "Jo'natish yo'q.": "Отгрузок нет.",
    Samarqand: "Самарканд",
    "Mashina raqami": "Номер машины",
    "+ Jo'natish qo'shish": "+ Добавить отгрузку",

    /* ---------- oylik hisobot ---------- */
    "Kunlik beton hajmi: reja va fakt": "Суточный объём бетона: план и факт",
    "{d}-kun: fakt {f} m³, reja {p} m³": "{d}-е число: факт {f} м³, план {p} м³",
    "Bu oyda kunlik hisobot yo'q": "В этом месяце нет ежедневных отчётов",
    "{d} dan keyin bu oyda kunlik hisobot yo'q": "После {d} в этом месяце нет ежедневных отчётов",
    Oy: "Месяц",
    "Oylik Excel (har kun alohida varaq)": "Месячный Excel (каждый день — отдельный лист)",
    "Hisobot CSV": "Отчёт CSV",
    "Kunlik beton hajmi, m³": "Суточный объём бетона, м³",
    "Mahsulotlar bo'yicha": "По изделиям",
    "Bu oyda yozuv yo'q.": "В этом месяце записей нет.",
    "Materiallar: haqiqiy sarf va norma": "Материалы: фактический расход и норма",
    "Oy boshida": "На начало месяца",
    "{m} — sarf": "{m} — расход",
    "m³": "м³",
    "Sarf (haqiqiy)": "Расход (факт)",
    "Sarf (norma)": "Расход (норма)",
    Farq: "Отклонение",
    "Oy oxirida": "На конец месяца",
    "Sarf qiymati, so'm": "Стоимость расхода, сум",
    "Sarflangan materiallar qiymati": "Стоимость израсходованных материалов",
    "«Farq» — haqiqiy sarf minus norma bo'yicha sarf. 10 % dan ortiq farq sariq bilan ajratilgan.": "«Отклонение» — фактический расход минус расход по норме. Отклонение более 10 % выделено жёлтым.",
    "Ishlab chiqarildi": "Произведено",
    "Reja bajarilishi": "Выполнение плана",
    "Beton (fakt)": "Бетон (факт)",

    /* ---------- qoldiq va ehtiyoj ---------- */
    "Boshlang'ich qoldiq saqlandi": "Начальный остаток сохранён",
    "Boshlang'ich qoldiq": "Начальный остаток",
    "Omborni hisoblash shu sananing BOSHIDAGI qoldiqdan boshlanadi. Undan oldingi kunlik hisobotlar hisobga olinmaydi.": "Учёт склада начинается с остатка НА НАЧАЛО этой даты. Более ранние ежедневные отчёты не учитываются.",
    "Tayyor mahsulot, dona": "Готовая продукция, шт",
    "Qoldiq {a} boshidagi boshlang'ich qoldiq + {b} oxirigacha barcha kunlik hisobotlar va ombor harakatlaridan hisoblandi.": "Остаток рассчитан: начальный остаток на {a} + все ежедневные отчёты и движения склада по {b} включительно.",
    "Boshlang'ich qoldiq kiritilmagan — hisob noldan boshlanadi.": "Начальный остаток не введён — учёт начинается с нуля.",
    "Materiallar qiymati": "Стоимость материалов",
    "Tayyor mahsulot": "Готовая продукция",
    "Tayyor mahsulot qiymati": "Стоимость готовой продукции",
    "Materiallar qoldig'i": "Остатки материалов",
    "Barcha guruhlar": "Все группы",
    "Qiymat, so'm": "Стоимость, сум",
    "Qoldiq, dona": "Остаток, шт",
    "Narx (QQS bilan)": "Цена (с НДС)",
    "Faol buyurtmalar uchun material ehtiyoji": "Потребность в материалах под активные заказы",
    "Faol buyurtmalarda qoldiq yo'q.": "По активным заказам остатка нет.",
    "Buyurtma qoldig'i (jo'natilmagan) minus ombordagi tayyor mahsulot =": "Остаток по заказам (не отгружено) минус готовая продукция на складе =",
    "hammasi omborda bor": "всё есть на складе",
    Kerak: "Нужно",
    Omborda: "На складе",
    Yetishmaydi: "Не хватает",
    "yetadi": "хватает",
    "holatiga": "на дату",

    /* ---------- buyurtmalar ---------- */
    "Avval «Katalog»ga mahsulot qo'shing": "Сначала добавьте изделие в «Каталог»",
    "Buyurtma №{n}": "Заказ №{n}",
    "Yangi buyurtma": "Новый заказ",
    Buyurtmachi: "Заказчик",
    "so'm/dona QQS bilan, 0 = kalkulyatsiyadan": "сум/шт с НДС, 0 = из калькуляции",
    "Qabul sanasi": "Дата приёма",
    Muddat: "Срок",
    "+ Yangi buyurtma": "+ Новый заказ",
    "Bu filtr bo'yicha buyurtma yo'q.": "По этому фильтру заказов нет.",
    " · kechikdi": " · просрочен",
    "Jami ({n} ta)": "Итого ({n} шт)",
    "«Jo'natildi» ustuni kunlik hisobotdagi shu buyurtmaga bog'langan jo'natishlardan hisoblanadi. Narx 0 bo'lsa, kalkulyatsiyadagi QQS bilan narx olinadi.": "Столбец «Отгружено» считается по отгрузкам в ежедневном отчёте, привязанным к заказу. Если цена 0, берётся цена с НДС из калькуляции.",
    "№": "№",
    Qoldi: "Осталось",

    /* ---------- kalkulyatsiya, katalog, mahsulot ---------- */
    "Mahsulotlar katalogi": "Каталог изделий",
    Marka: "Марка",
    "Beton, m³": "Бетон, м³",
    "Metall, kg": "Металл, кг",
    "Og'irligi, t": "Вес, т",
    "Og'irlik taxminan: beton hajmi × 2,5 t/m³ + metall.": "Вес приблизительно: объём бетона × 2,5 т/м³ + металл.",
    Norma: "Норма",
    Tannarx: "Себестоимость",
    "Narx QQS bilan": "Цена с НДС",
    "Kalkulyatsiya kiritilmagan. «Tahrirlash» orqali materiallarni qo'shing.": "Калькуляция не заполнена. Добавьте материалы через «Изменить».",
    "Excel faylidagi narx: {p} so'm — farq {d} so'm": "Цена в файле Excel: {p} сум — разница {d} сум",
    "Excel faylidagi narx: {p} so'm — mos.": "Цена в файле Excel: {p} сум — совпадает.",
    "Qator turlari:": "Типы строк:",
    "Qidirish: Ф5, лоток…": "Поиск: Ф5, лоток…",
    "Другие затраты, jami": "Другие затраты, итого",
    "Итого (tannarx)": "Итого (себестоимость)",
    "Hisoblash turi": "Способ расчёта",
    "Marka kiritilmagan": "Не указана марка",
    "{c} — tahrirlash": "{c} — изменение",
    "Yangi mahsulot": "Новое изделие",
    "Sarf normasi (Норма)": "Норма расхода",
    "Kalkulyatsiya ·": "Калькуляция ·",
    "1 dona uchun sarf": "Расход на 1 шт",
    "+ Material": "+ Материал",
    "+ Qator": "+ Строка",
    "Avtomatik qo'shiladi": "Добавляется автоматически",
    "Beton yoki metall qo'shilganda bu yerda qum, sement, sheben va elektrod chiqadi.": "При добавлении бетона или металла здесь появятся песок, цемент, щебень и электрод.",
    "Qum, sement, sheben — beton markasi koeffitsiyentlaridan («Materiallar» bo'limi). Elektrod — metall og'irligining": "Песок, цемент, щебень — по коэффициентам марки бетона (раздел «Материалы»). Электрод — от веса металла:",
    "Sarf normasidan nusxa olish": "Скопировать из нормы расхода",
    "Metall og'irligi": "Вес металла",
    "(kg, «Логистика метала» uchun)": "(кг, для «Логистика метала»)",
    Hisoblash: "Расчёт",
    "Tannarx:": "Себестоимость:",
    "Narx QQSsiz:": "Цена без НДС:",
    "Narx QQS bilan:": "Цена с НДС:",

    /* ---------- materiallar ---------- */
    "— material —": "— материал —",
    "(so'm /": "(сум /",
    "Omborda hisobga olinadi": "Учитывается на складе",
    "Elektrod normasi shu metalldan hisoblanadi": "Норма электрода считается от этого металла",
    "Bu material — elektrod (norma metall og'irligidan avtomatik)": "Этот материал — электрод (норма автоматически от веса металла)",
    "1 m³ narxi uchun tarkib (kalkulyatsiya)": "Состав для цены 1 м³ (калькуляция)",
    "1 m³ narxi:": "Цена 1 м³:",
    "1 m³ uchun ombordan yoziladi (Норма)": "Списывается со склада на 1 м³ (Норма)",
    "Kunlik hisobotdagi «Norma» ustuni va material ehtiyoji shu koeffitsiyentlar bilan hisoblanadi.": "Столбец «Норма» в ежедневном отчёте и потребность в материалах считаются по этим коэффициентам.",
    "Sozlamalar saqlandi": "Настройки сохранены",
    "Materiallar va narxlar": "Материалы и цены",
    "+ Material qo'shish": "+ Добавить материал",
    "Narx, so'm": "Цена, сум",
    "narx yo'q": "нет цены",
    retseptdan: "по рецепту",
    "Elektrod normasi": "Норма электрода",
    "(% metall og'irligidan)": "(% от веса металла)",
    "Korxona nomi (chop etishda)": "Название предприятия (для печати)",
    "Imzo qo'yuvchilar (har biri yangi qatorda)": "Подписанты (каждый с новой строки)",
    "Sozlamalarni saqlash": "Сохранить настройки",
    Sozlamalar: "Настройки",
    "Material saqlandi": "Материал сохранён",

    /* ---------- boshqaruv ---------- */
    "Ishlab chiqarish": "Производство",
    "Jo'natish": "Отгрузка",
    "omborda hisoblanadi": "учитывается на складе",
    "elektrod asosi": "база электрода",
    "retsept (1 m³)": "рецепт (1 м³)",
    "Sarf normasi": "Норма расхода",
    "metall, kg": "металл, кг",
    "ishlab chiqarish xarajatlari": "производственные затраты",
    "boshqa xarajatlar": "прочие затраты",
    "marja, %": "маржа, %",
    "QQS, %": "НДС, %",
    "elektrod, %": "электрод, %",
    "parolni almashtirishi kerak": "должен сменить пароль",
    "kalkulyatsiya andozasi": "шаблон калькуляции",
    "minimal qoldiq": "минимальный остаток",
    "bo'lim / sex": "подразделение / цех",
    "mas'ul shaxs": "ответственный",
    "yetkazib beruvchi": "поставщик",
    reja_: "план",
    izoh: "примечание",
    sarf: "расход",
    kirim: "приход",
    soni: "кол-во",
    buyurtmachi: "заказчик",
    mashina: "машина",
    buyurtma: "заказ",
    mahsulot: "изделие",
    material: "материал",
    nomi: "название",
    birlik: "ед.",
    guruh: "группа",
    narx: "цена",
    elektrod: "электрод",
    norma: "норма",
    marka: "марка",
    materiallar: "материалы",
    holat: "статус",
    muddat: "срок",
    sana: "дата",
    korxona: "предприятие",
    imzolar: "подписи",
    rol: "роль",
    faol: "активен",
    login: "логин",
    parol: "пароль",
    qiymat: "значение",
    turi: "тип",
    tartib: "порядок",
    izohlar: "примечания",
    arxivda: "в архиве",
    texnika: "техника",
    nakladnoy: "накладная",
    Foydalanuvchi: "Пользователь",
    "Zaxira nusxa": "Резервная копия",
    "Ombor harakati": "Движение склада",
    "Sex / texnika": "Цех / техника",
    "Qo'shildi": "Добавлено",
    "O'zgardi": "Изменено",
    Kirdi: "Вход",
    "Yuklab olindi": "Скачано",
    "{n}-qator": "строка {n}",
    "Foydalanuvchi: {u}": "Пользователь: {u}",
    "Yangi foydalanuvchi": "Новый пользователь",
    "Ism familiya": "Имя и фамилия",
    Rol: "Роль",
    "lotin harflari": "латинскими буквами",
    "Vaqtinchalik parol": "Временный пароль",
    "kamida 6 belgi": "не менее 6 символов",
    "Foydalanuvchi qo'shildi — birinchi kirishda parolini o'zgartiradi": "Пользователь добавлен — при первом входе сменит пароль",
    "{u} — yangi parol": "{u} — новый пароль",
    "Yangi vaqtinchalik parol": "Новый временный пароль",
    "Parolni o'rnatish": "Установить пароль",
    "Parol o'rnatildi. Foydalanuvchi keyingi kirishda uni o'zgartiradi": "Пароль установлен. Пользователь сменит его при следующем входе",
    Foydalanuvchilar: "Пользователи",
    "Foydalanuvchi qo'shish": "Добавить пользователя",
    Ism: "Имя",
    "Oxirgi kirish": "Последний вход",
    "bu siz": "это вы",
    "O'chirilgan": "Отключён",
    Bloklash: "Заблокировать",
    Faollashtirish: "Включить",
    "hamma narsani va foydalanuvchilarni boshqaradi.": "управляет всем, включая пользователей.",
    "hisobot, ombor, buyurtma, katalog va materiallarni tahrirlaydi.": "редактирует отчёты, склад, заказы, каталог и материалы.",
    "ombor kirim-chiqimini, sex va texnikani yuritadi.": "ведёт приход и расход склада, цеха и технику.",
    "va": "и",
    "hamma bo'limni ko'radi, lekin hech narsani o'zgartira olmaydi. Bloklangan foydalanuvchi darhol tizimdan chiqariladi.": "видят все разделы, но ничего не могут менять. Заблокированный пользователь сразу выходит из системы.",
    "O'zgarishlar tarixi": "История изменений",
    "Bo'lim": "Раздел",
    "Barcha bo'limlar": "Все разделы",
    "Barcha foydalanuvchilar": "Все пользователи",
    "Hozircha yozuv yo'q.": "Записей пока нет.",
    Vaqt: "Время",
    Kim: "Кто",
    Amal: "Действие",
    Nima: "Что",
    Farqlar: "Изменения",
    yopish: "скрыть",
    "… yana {n} ta o'zgarish": "… ещё {n} изменений",
    "Yana ko'rsatish": "Показать ещё",
    "Qatorni bosing — nima, qaysi qiymatdan qaysi qiymatga o'zgargani ko'rinadi. Yozuvlar 13 oy saqlanadi.": "Нажмите на строку — увидите, что и с какого значения на какое изменилось. Записи хранятся 13 месяцев.",
    "{f} yuklab olindi": "{f} скачан",
    "Butun bazani bitta faylga yuklab olish": "Скачать всю базу одним файлом",
    "Materiallar, mahsulotlar, barcha kunlik hisobotlar, buyurtmalar va sozlamalar. Parollar faylga yozilmaydi.": "Материалы, изделия, все ежедневные отчёты, заказы, склад и настройки. Пароли в файл не попадают.",
    "Hali birorta ham zaxira nusxa olinmagan.": "Резервных копий ещё не было.",
    "Oxirgi nusxa: {d} ({u})": "Последняя копия: {d} ({u})",
    " — {n} kun oldin, yangisini oling": " — {n} дн. назад, сделайте новую",
    "Zaxiradan qanday tiklanadi?": "Как восстановить из копии?",
    "Faylni kompyuterdagi": "Скопируйте файл в папку",
    "papkasiga nusxalang.": "на компьютере.",
    "Avval tekshiring (hech narsa o'zgarmaydi):": "Сначала проверьте (ничего не изменится):",
    "Tiklash:": "Восстановить:",
    "Tiklashda bazadagi hozirgi ma'lumotlar zaxiradagisi bilan almashtiriladi. Foydalanuvchilar tegilmaydi.": "При восстановлении текущие данные заменяются данными из копии. Пользователи не затрагиваются.",

    /* ---------- parol, o'rnatish ---------- */
    "Yangi parollar bir xil emas": "Новые пароли не совпадают",
    "Yangi parol o'rnating": "Установите новый пароль",
    "Parolni o'zgartirish": "Смена пароля",
    "Siz vaqtinchalik parol bilan kirdingiz. Davom etish uchun o'zingizning parolingizni o'rnating.": "Вы вошли с временным паролем. Чтобы продолжить, установите свой пароль.",
    "Joriy parol": "Текущий пароль",
    "Yangi parol": "Новый пароль",
    "(kamida 6 belgi)": "(не менее 6 символов)",
    "Yangi parol (yana bir marta)": "Новый пароль (ещё раз)",
    "Telefonga ilova qilib o'rnating": "Установите как приложение на телефон",
    "Safari pastidagi": "Нажмите внизу Safari кнопку",
    "tugmasini bosing, so'ng": ", затем выберите",
    "ni tanlang.": ".",
    "Bosh ekranda ikonka paydo bo'ladi va ilova brauzersiz ochiladi.": "На главном экране появится значок, и приложение будет открываться без браузера.",
    "O'rnatish": "Установить",

    /* ---------- Excel eksport ---------- */
    "Narxlar ro'yxati": "Прайс-лист",
    "Narxlar ro'yxati (Excel)": "Прайс-лист (Excel)",
    "Mahsulotlar narxlari (kalkulyatsiya bo'yicha)": "Цены изделий (по калькуляции)",
    "Narx QQSsiz": "Цена без НДС",
    "Narx bo'sh bo'lsa — kalkulyatsiya kiritilmagan.": "Пустая цена — калькуляция не заполнена.",
    "Excel faylni yuklab olish": "Скачать файл Excel",
    "Telegram, pochta va boshqalarga yuborish": "Отправить в Telegram, по почте и т.д.",
    "Oylik xulosa (Excel)": "Итоги месяца (Excel)",
    "Xulosani ulashish": "Поделиться итогами",
    "Oylik hisobot — {p}: mahsulotlar": "Месячный отчёт — {p}: изделия",
    "Oylik hisobot — {p}: materiallar": "Месячный отчёт — {p}: материалы",
    "Ishlab chiqarildi: {f} dona, reja bajarilishi {r} %, beton {b} m³, jo'natildi {s} dona": "Произведено: {f} шт, выполнение плана {r} %, бетон {b} м³, отгружено {s} шт",
    "Kirim-chiqim": "Приход-расход",
    "Material bo'yicha": "По материалам",
    "Material bo'yicha jami": "Итого по материалам",
    "Materiallar qoldig'i — {d} holatiga": "Остатки материалов на {d}",
    "Tayyor mahsulot qoldig'i — {d} holatiga": "Остатки готовой продукции на {d}",
    Ehtiyoj: "Потребность",
    "Ombor qoldig'i": "Остатки склада",
    "Ombor qoldig'i — {d} holatiga": "Остатки склада на {d}",
    Tayyorlandi: "Сформировано",
    "Ma'lumot yo'q": "Нет данных",
    /* ---------- metr → kg ---------- */
    metr: "метр",
    m: "м",
    "kg/m": "кг/м",
    avtomatik: "автоматически",
    birlik: "ед.",
    "ПТО kiritgan koeffitsiyent": "Коэффициент задан ПТО",
    "1 metr og'irligi": "Вес 1 метра",
    "kg/m — omborchi metrda yozsa": "кг/м — если кладовщик вводит в метрах",
    "Bo'sh qoldirilsa — avtomatik": "Если пусто — автоматически",
    "Metrdan aylantirish kerak bo'lsa, kiriting": "Заполните, если нужен пересчёт из метров",
    Metrda: "В метрах",
    "Bu material uchun metrdan aylantirish koeffitsiyenti yo'q": "Для этого материала нет коэффициента пересчёта из метров",
    "Sex boshlig'i (usta)": "Начальник цеха (мастер)",
    "kunlik rejani tuzadi, faktni, xomashyo sarfini va izohni yozadi (jo'natish va kirimni o'zgartira olmaydi).": "составляет дневной план, вносит факт, расход сырья и примечания (отгрузку и приход менять не может).",
    /* ---------- server xabarlari ---------- */
    "Login yoki parol noto'g'ri": "Неверный логин или пароль",
    "Login va parolni kiriting": "Введите логин и пароль",
    "Foydalanuvchi yo'q. Birinchi kirish uchun serverda APP_PASSWORD ni o'rnating": "Пользователей нет. Для первого входа задайте APP_PASSWORD на сервере",
    "Qaytadan kiring": "Войдите заново",
    "Avval o'zingizning parolingizni o'rnating": "Сначала установите свой пароль",
    "Sizda bu amal uchun ruxsat yo'q": "У вас нет прав на это действие",
    "Bu bo'lim faqat administrator uchun": "Этот раздел только для администратора",
    "Yozuv topilmadi": "Запись не найдена",
    "Joriy parol noto'g'ri": "Неверный текущий пароль",
    "Yangi parol eskisidan farq qilsin": "Новый пароль должен отличаться от старого",
    "Parol kamida 6 belgidan iborat bo'lsin": "Пароль — не менее 6 символов",
    "Parol juda uzun": "Пароль слишком длинный",
    "Rol noto'g'ri": "Неверная роль",
    "Kamida bitta faol administrator qolishi kerak": "Должен остаться хотя бы один активный администратор",
    "O'zingizni o'chira olmaysiz": "Нельзя удалить самого себя",
    "Material normalarda, retseptda, kunlik hisobotda yoki ombor tarixida ishlatilgan — o'chirib bo'lmaydi. Uni arxivga o'tkazing.": "Материал используется в нормах, рецептах, ежедневных отчётах или истории склада — удалить нельзя. Переведите его в архив.",
    "Mahsulot buyurtma yoki kunlik hisobotda ishlatilgan — o'chirib bo'lmaydi": "Изделие используется в заказах или ежедневных отчётах — удалить нельзя",
    "Sana formati YYYY-MM-DD": "Формат даты ГГГГ-ММ-ДД",
    "from va to sanalarini YYYY-MM-DD formatida bering": "Укажите даты from и to в формате ГГГГ-ММ-ДД",
    "Harakat turi noto'g'ri (kirim yoki chiqim)": "Неверный тип движения (приход или расход)",
    "Material topilmadi": "Материал не найден",
    "Bu material omborda hisobga olinmaydi": "Этот материал не учитывается на складе",
    "Bo'lim topilmadi": "Подразделение не найдено",
    "Texnika topilmadi": "Техника не найдена",
    "Faqat o'zingiz kiritgan yozuvni 24 soat ichida bekor qila olasiz": "Отменить можно только свою запись и только в течение 24 часов",
    "Bu kirimdan keyin material ishlatilgan — bekor qilsangiz qoldiq manfiy bo'lib qoladi": "После этого прихода материал уже расходовался — при отмене остаток станет отрицательным",
    "Mahsulot topilmadi": "Изделие не найдено",
    "Kalkulyatsiya andozasi noto'g'ri": "Неверный шаблон калькуляции",
    "Boshlang'ich qoldiq sanasi noto'g'ri": "Неверная дата начального остатка",
    "Bunday API yo'li yo'q": "Такого адреса API нет",
    "Bunday yozuv allaqachon bor": "Такая запись уже есть",
    "JSON noto'g'ri": "Неверный JSON",
    "Serverda xatolik": "Ошибка на сервере",
    "Ma'lumotlar bazasiga ulanib bo'lmadi — MONGODB_URI va Atlas Network Access (0.0.0.0/0) ni tekshiring": "Нет связи с базой данных — проверьте MONGODB_URI и Atlas Network Access (0.0.0.0/0)",
    "Material normalarda, retseptda yoki kunlik hisobotda ishlatilgan — o'chirib bo'lmaydi": "Материал используется — удалить нельзя",
    "Buyurtmachi kiritilmagan": "Не указан заказчик",
    "Login faqat lotin harflari, raqam, nuqta, _ va - dan iborat bo'lsin": "Логин — только латинские буквы, цифры, точка, _ и -",
    "Login kamida 3 belgi": "Логин — не менее 3 символов",
    "Login kiritilmagan": "Не указан логин",
    "Manfiy son kiritib bo'lmaydi": "Отрицательное число недопустимо",
    "Miqdor 0 dan katta bo'lishi kerak": "Количество должно быть больше 0",
    "Nomi kiritilmagan": "Не указано название",
    "Soni kamida 1": "Количество — не менее 1",
    "Soni kamida 1 bo'lishi kerak": "Количество должно быть не менее 1",
    // --- rollar ---
    "Rahbar (to'liq huquq)": "Руководитель (полные права)",
    "Kuzatuvchi (ko'rish va yuklab olish)": "Наблюдатель (просмотр и выгрузка)",
    "Kuzatuvchi": "Наблюдатель",
    "hamma bo'limni ko'radi va Excel qilib yuklab oladi, lekin hech narsani o'zgartira olmaydi. Bloklangan foydalanuvchi darhol tizimdan chiqariladi.": "видят все разделы и выгружают их в Excel, но ничего не могут изменить. Заблокированный пользователь сразу выходит из системы.",
    // --- xarajat andozalari ---
    "Yangi andoza": "Новый шаблон",
    "Bu andozada {n} ta mahsulot bor — avval ularni boshqa andozaga o'tkazing": "В этом шаблоне {n} изд. — сначала переведите их в другой шаблон",
    "Andoza nomi kiritilmagan": "Не указано название шаблона",
    "Saqlandi — {n} ta mahsulot narxi qayta hisoblandi": "Сохранено — цены пересчитаны для {n} изд.",
    "Xarajat andozalari": "Шаблоны затрат",
    "+ Yangi andoza": "+ Новый шаблон",
    "Andoza nomi": "Название шаблона",
    "«Summa» ustuni namuna uchun: {c} (1 dona). Narx QQS bilan: {p} so'm.": "Столбец «Сумма» — для образца: {c} (1 шт). Цена с НДС: {p} сум.",
    "Bu andozaga hali mahsulot bog'lanmagan.": "К этому шаблону ещё не привязаны изделия.",
    "Andozani o'chirish": "Удалить шаблон",
    "Mahsulotlar qaysi andozada": "Какие изделия в каком шаблоне",
    "— guruh —": "— группа —",
    "Andoza": "Шаблон",
    "andoza": "шаблон",
    "Alohida": "Отдельно",
    "Guruhning hammasiga": "Всей группе",
    "hozir {v}": "сейчас {v}",
    "{n} ta mahsulot narxi o'zgaradi": "Изменится цена {n} изд.",
    "Narxlar o'zgarmaydi": "Цены не изменятся",
    "Xarajat andozasi": "Шаблон затрат",
    "Alohida (faqat shu mahsulot uchun)": "Отдельно (только для этого изделия)",
    "Quyidagi xarajatlar «{n}» andozasidan olinadi. Ularni o'zgartirish — «Kalkulyatsiya» → «Xarajat andozalari» (shu andozadagi barcha mahsulotlarga ta'sir qiladi).": "Эти затраты берутся из шаблона «{n}». Изменить их — «Калькуляция» → «Шаблоны затрат» (затронет все изделия этого шаблона).",
    "xarajatlar alohida": "затраты заданы отдельно",
    "Производственная СС, Другие затраты, marja va QQS shu yerda bir marta kiritiladi — andozaga bog'langan barcha mahsulotlar kalkulyatsiyasi avtomatik yangilanadi. Mahsulotning o'zida faqat materiallar va metall og'irligi qoladi.": "Производственная СС, Другие затраты, маржа и НДС задаются здесь один раз — калькуляция всех изделий шаблона обновляется автоматически. В самом изделии остаются только материалы и вес металла.",
    "Mahsulot tanlanmagan": "Изделия не выбраны",
    "Bunday andoza yo'q": "Такого шаблона нет",
    "Andozalar ro'yxati noto'g'ri": "Неверный список шаблонов",
    "Andoza kodi noto'g'ri": "Неверный код шаблона",
    // --- grafiklar ---
    "Oldingi oy": "Предыдущий месяц",
    "Keyingi oy": "Следующий месяц",
    "{m} — kunma-kun. Boshqa oyni yuqoridagi oy tanlagichdan tanlang.": "{m} — по дням. Другой месяц выберите вверху.",
    "{m}: kunma-kun ko'rsatkichlar": "{m}: показатели по дням",
    "Oy noto'g'ri": "Неверный месяц",
    "Yan": "Янв",
    "Fev": "Фев",
    "Mar": "Мар",
    "Apr": "Апр",
    "May": "Май",
    "Iyun": "Июн",
    "Iyul": "Июл",
    "Avg": "Авг",
    "Sen": "Сен",
    "Okt": "Окт",
    "Noy": "Ноя",
    "Dek": "Дек",
    "Yanvar": "Январь",
    "Fevral": "Февраль",
    "Mart": "Март",
    "Aprel": "Апрель",
    "Avgust": "Август",
    "Sentyabr": "Сентябрь",
    "Oktyabr": "Октябрь",
    "Noyabr": "Ноябрь",
    "Dekabr": "Декабрь",
    "Xomashyo (sement, qum, sheben)": "Сырьё (цемент, песок, щебень)",
    "{n} oy": "{n} мес.",
    "Ishlab chiqarildi — {m}": "Произведено — {m}",
    "o'tgan oy: {v}": "прошлый месяц: {v}",
    "Brak ulushi": "Доля брака",
    "Material xarajati": "Затраты на материалы",
    "Reja va fakt, dona": "План и факт, шт",
    "Reja bajarilishi, %": "Выполнение плана, %",
    "Material xarajati, so'm": "Затраты на материалы, сум",
    "Ishlab chiqarish sarfi va ombor chiqimi, joriy narxlarda. Xomashyo — sement, qum, sheben": "Производственный расход и расход со склада, в текущих ценах. Сырьё — цемент, песок, щебень",
    "Xomashyo": "Сырьё",
    "1 m³ betonga material xarajati, ming so'm": "Затраты материалов на 1 м³ бетона, тыс. сум",
    "Ishlab chiqarish sarfi ÷ quyilgan beton hajmi": "Производственный расход ÷ объём уложенного бетона",
    "1 m³ uchun": "На 1 м³",
    "Quyilgan beton, m³": "Уложено бетона, м³",
    "Brak ulushi, %": "Доля брака, %",
    "Brak ÷ (sifatli + brak)": "Брак ÷ (годные + брак)",
    "Jo'natildi, dona": "Отгружено, шт",
    "Omborga kirim (xarid), so'm": "Приход на склад (закупки), сум",
    "Grafik ustiga bosing (yoki sichqonchani olib boring) — o'sha oyning aniq qiymatlari chiqadi. «Jadval» — raqamlar jadval ko'rinishida. Joriy oy hali tugamagan — uni o'tgan oylar bilan solishtirishda buni hisobga oling.": "Нажмите на график (или наведите курсор) — появятся точные значения за месяц. «Таблица» — те же данные в виде таблицы. Текущий месяц ещё не закончился — учитывайте это при сравнении с прошлыми.",
    "Ko'rsatkichlar": "Показатели",
    "Oyma-oy asosiy ko'rsatkichlar": "Основные показатели по месяцам",
    "Bajarilishi, %": "Выполнение, %",
    "1 m³ ga, so'm": "На 1 м³, сум",
    "Kirim (xarid), so'm": "Приход (закупки), сум",
    "Material xarajati joriy narxlarda hisoblangan.": "Затраты на материалы рассчитаны в текущих ценах.",
    "Grafik": "График",
    "Jadval": "Таблица",
    "Belgilar": "Обозначения",
    "Grafiklar": "Графики",
    "mln": "млн",
    // --- texnika hisobi ---
    "Ta'mir": "Ремонт",
    "Texnik xizmat (TO)": "Техобслуживание (ТО)",
    "Ko'rsatkich": "Показание",
    "l/100 km": "л/100 км",
    "l/soat": "л/моточас",
    "l": "л",
    "km": "км",
    "soat": "моточ.",
    "Yoqilg'i": "Топливо",
    "Ehtiyot qism va ta'mir": "Запчасти и ремонт",
    "Normadan ortiq sarf": "Перерасход нормы",
    "Texnik xizmat vaqti": "Пора на ТО",
    "Texnika qo'shilmagan. «Sex va texnika» bo'limida mashinalarni kiriting.": "Техника не добавлена. Внесите машины в разделе «Цеха и техника».",
    "ko'rsatkich yo'q": "нет показаний",
    "davrda {n}": "за период {n}",
    "TO muddati o'tgan": "ТО просрочено",
    "TO yaqin: {n}": "ТО скоро: {n}",
    "so'm · {n} l": "сум · {n} л",
    "Sarf «quyishdan quyishgacha» hisoblanadi: yoqilg'i berilganda spidometr (motosoat) ko'rsatkichi yozilsa, keyingi quyishgacha yurilgan masofaga bo'linadi. Normadan 10% dan ortiq sarf qizil bilan belgilanadi. Normani va texnik xizmat oralig'ini «Sex va texnika» bo'limida kiriting.": "Расход считается «от заправки до заправки»: если при выдаче топлива записано показание спидометра (моточасов), топливо делится на пробег до следующей заправки. Перерасход более 10% выделяется красным. Норму и интервал ТО задайте в разделе «Цеха и техника».",
    "Motosoat": "Моточасы",
    "Spidometr, km": "Спидометр, км",
    "O'rtacha sarf": "Средний расход",
    "norma {n}": "норма {n}",
    "norma kiritilmagan": "норма не задана",
    "oraliq kiritilmagan": "интервал не задан",
    "Navbatdagi TO": "Следующее ТО",
    "{n} o'tib ketdi": "просрочено на {n}",
    "{n} qoldi": "осталось {n}",
    "Davrdagi xarajat": "Затраты за период",
    "yoqilg'i {a} · qism {b} · ta'mir {c}": "топливо {a} · запчасти {b} · ремонт {c}",
    "Ta'mir / TO yozish": "Записать ремонт / ТО",
    "Ko'rsatkich kiritish": "Внести показание",
    "Xarajat": "Затраты",
    "so'm, tashqi xizmat": "сум, сторонние услуги",
    "Masalan: moy va filtrlar almashtirildi": "Например: заменены масло и фильтры",
    "Ombordan olingan ehtiyot qism va moylar chiqim sifatida shu texnikaga yoziladi — bu yerga faqat tashqi xizmat haqini kiriting.": "Запчасти и масла со склада списываются на эту технику расходом — здесь указывайте только оплату сторонних услуг.",
    "Yoqilg'i sarfi (quyishdan quyishgacha)": "Расход топлива (от заправки до заправки)",
    "Yurdi": "Пробег",
    "Quyildi, l": "Заправлено, л",
    "Ombordan berilgan": "Выдано со склада",
    "Bu davrda berilmagan.": "За период ничего не выдавалось.",
    "Ta'mir va texnik xizmat": "Ремонт и ТО",
    "Bu davrda yozuv yo'q.": "За период записей нет.",
    "Texnika bo'yicha xarajat va yoqilg'i sarfi": "Затраты и расход топлива по технике",
    "Yoqilg'i, l": "Топливо, л",
    "Yoqilg'i, so'm": "Топливо, сум",
    "Normaga, %": "К норме, %",
    "Ehtiyot qism, so'm": "Запчасти, сум",
    "Ta'mir, so'm": "Ремонт, сум",
    "Jami, so'm": "Итого, сум",
    "Quyishlar": "Заправки",
    "Yoqilg'i sarfi: quyishdan quyishgacha": "Расход топлива: от заправки до заправки",
    "Ko'rsatkich (dan)": "Показание (с)",
    "Ko'rsatkich (gacha)": "Показание (по)",
    "Hisoblagich": "Счётчик",
    "Yoqilg'i normasi, l/soat": "Норма топлива, л/моточас",
    "Yoqilg'i normasi, l/100 km": "Норма топлива, л/100 км",
    "Texnik xizmat har … soatda": "ТО каждые … моточасов",
    "Texnik xizmat har … km da": "ТО каждые … км",
    "yoqilg'i sarfini hisoblash uchun": "для расчёта расхода топлива",
    "Oxirgi: {m} ({d})": "Последнее: {m} ({d})",
    "yurgan: {n}": "пробег: {n}",
    "Texnika hisobi": "Учёт техники",
    "Yoqilg'i sarfi normaga nisbatan, ta'mir va texnik xizmat": "Расход топлива к норме, ремонт и ТО",
    "Spidometr / motosoat ko'rsatkichi noto'g'ri": "Неверное показание спидометра / моточасов",
    "Ko'rsatkichni kiriting": "Введите показание",
    // --- tayyor mahsulot va brak ---
    "Bu oy": "Этот месяц",
    "O'tgan oy": "Прошлый месяц",
    "Brak": "Брак",
    "Tannarx bo'yicha qiymati": "Стоимость по себестоимости",
    "Buyurtmalarga band": "Зарезервировано под заказы",
    "Bo'sh (sotish mumkin)": "Свободно (можно продать)",
    "Omborda tayyor mahsulot yo'q.": "Готовой продукции на складе нет.",
    "Band": "В резерве",
    "Bo'sh": "Свободно",
    "Qiymati": "Стоимость",
    "yetmaydi {n}": "не хватает {n}",
    "Qoldiq = boshlang'ich + sifatli fakt − jo'natilgan − brakka chiqarilgan. «Band» — faol buyurtmalarning jo'natilmagan qismi. Qiymat kalkulyatsiyadagi tannarx (marja va QQSsiz) bo'yicha.": "Остаток = начальный + годный факт − отгружено − списано в брак. «В резерве» — неотгруженная часть активных заказов. Стоимость — по себестоимости из калькуляции (без маржи и НДС).",
    "Jami brak": "Всего брака",
    "Ishlab chiqarishda brak ulushi": "Доля брака в производстве",
    "Ombordan brakka chiqarildi": "Списано со склада в брак",
    "Zarar (tannarx bo'yicha)": "Убыток (по себестоимости)",
    "Bu davrda brak yo'q.": "За период брака нет.",
    "Sabablar bo'yicha": "По причинам",
    "Sifatli": "Годные",
    "Ombordan": "Со склада",
    "Zarar, so'm": "Убыток, сум",
    "Brak yozuvlari": "Записи о браке",
    "Ishlab chiqarishdagi brak kunlik hisobotda «Brak» ustuniga yoziladi — u omborga kirmaydi, lekin material sarfiga qo'shiladi. Ombordagi tayyor mahsulot keyin yaroqsiz bo'lsa (tashishda singan va h.k.), mahsulot kartasidan «Brakka chiqarish» bilan yoziladi.": "Производственный брак записывается в ежедневном отчёте в столбце «Брак» — на склад он не поступает, но учитывается в расходе материалов. Если готовое изделие стало негодным позже (разбито при перевозке и т. п.), его списывают из карточки изделия кнопкой «Списать в брак».",
    "Brakka chiqarildi": "Списано в брак",
    "Brakka chiqarish": "Списать в брак",
    "Sababi": "Причина",
    "Oxirgi 30 kun": "Последние 30 дней",
    "Bu davrda harakat yo'q.": "За период движений нет.",
    "ombordan {n}": "со склада {n}",
    "Yetmaydi": "Не хватает",
    "Tannarx, so'm": "Себестоимость, сум",
    "Qiymati, so'm": "Стоимость, сум",
    "Brak hisoboti: mahsulotlar": "Отчёт о браке: изделия",
    "Sifatli, dona": "Годные, шт",
    "Brak (ishlab chiqarishda)": "Брак (в производстве)",
    "Brak, %": "Брак, %",
    "Ombordan brakka": "Списано со склада",
    "Qayerda": "Где",
    "Brak, dona": "Брак, шт",
    "Brak sababi": "Причина брака",
    "brak −{n}": "брак −{n}",
    "Yoriq (darz ketgan)": "Трещина",
    "O'lchami noto'g'ri": "Неверные размеры",
    "Armatura ochiq qolgan": "Оголённая арматура",
    "Beton sifati past": "Низкое качество бетона",
    "Qolipdan chiqarishda shikastlangan": "Повреждено при распалубке",
    "Tashish / yuklashda singan": "Разбито при перевозке / погрузке",
    "Saqlashda shikastlangan": "Повреждено при хранении",
    "Boshqa sabab": "Другая причина",
    "Qoldiq, buyurtmalarga band va brak hisobi": "Остатки, резерв под заказы и учёт брака",
    "Sana noto'g'ri": "Неверная дата",
    "ishlab chiqarishda": "в производстве",
    "ombordan chiqarildi": "списано со склада",
    "dona omborda": "шт на складе",
    // --- inventarizatsiya, ta'minotchilar ---
    "Inventarizatsiya": "Инвентаризация",
    "+ Yangi inventarizatsiya": "+ Новая инвентаризация",
    "Ombordagi haqiqiy qoldiqni sanab kiriting. Hisobdagidan farqi (kamomad yoki ortiqcha) ko'rinadi. ПТО yoki administrator tasdiqlagach, qoldiq haqiqiyga tenglashtiriladi va farq kirim-chiqim tarixida «Inventarizatsiya» deb yoziladi.": "Посчитайте фактический остаток на складе. Будет видно расхождение с учётом (недостача или излишек). После утверждения ПТО или администратором учётный остаток приравнивается к фактическому, а разница записывается в историю движения как «Инвентаризация».",
    "Hali inventarizatsiya o'tkazilmagan.": "Инвентаризаций пока не было.",
    "sanaldi {a} / {b}": "посчитано {a} / {b}",
    "Tasdiqlangan": "Утверждена",
    "Qoralama": "Черновик",
    "Qaysi materiallar": "Какие материалы",
    "Yashirin sanash": "Слепой пересчёт",
    "omborchi hisobdagi qoldiqni ko'rmaydi, faqat sanaganini yozadi": "кладовщик не видит учётный остаток, только вносит посчитанное",
    "Boshlash": "Начать",
    "Tasdiqlandi — {n} ta material qoldig'i to'g'rilandi": "Утверждено — скорректирован остаток {n} мат.",
    "Inventarizatsiya bekor qilindi": "Инвентаризация отменена",
    "Saqlanmagan o'zgarishlar bor. Chiqib ketilsinmi?": "Есть несохранённые изменения. Выйти?",
    "Ro'yxat": "Список",
    "Sanaldi": "Посчитано",
    "Farqli materiallar": "С расхождением",
    "Kamomad": "Недостача",
    "Ortiqcha": "Излишек",
    "Sanalmagan": "Не посчитано",
    "Farqli": "С расхождением",
    "Hisobda": "По учёту",
    "Haqiqatda": "Фактически",
    "Farq, so'm": "Разница, сум",
    "{m}: haqiqatda": "{m}: фактически",
    "Hisobdagiga teng": "Равно учётному",
    "Tasdiqni bekor qilish": "Отменить утверждение",
    "Sanab bo'lgach saqlang — ПТО tekshirib tasdiqlaydi.": "После пересчёта сохраните — ПТО проверит и утвердит.",
    "Tasdiqlanganda faqat sanalgan materiallar to'g'rilanadi; sanalmaganlar o'zgarmaydi.": "При утверждении корректируются только посчитанные материалы; остальные не меняются.",
    "Ha, qoldiqni to'g'rilash": "Да, скорректировать остаток",
    "Tasdiqlash va qoldiqni to'g'rilash": "Утвердить и скорректировать остаток",
    "Inventarizatsiya dalolatnomasi №{n}": "Инвентаризационная опись №{n}",
    "yashirin": "слепая",
    "yashirin sanash": "слепой пересчёт",
    "boshladi": "начал(а)",
    "tasdiqladi": "утвердил(а)",
    "3 oy": "3 месяца",
    "1 yil": "1 год",
    "Yangi ta'minotchi": "Новый поставщик",
    "Telefon": "Телефон",
    "STIR (INN)": "ИНН",
    "STIR": "ИНН",
    "Kirimlarda ishlatilgan — arxivga olindi": "Используется в приходах — перенесён в архив",
    "Xaridlar": "Закупки",
    "Ta'minotchilar": "Поставщики",
    "Narxi oshgan": "Цена выросла",
    "+ Ta'minotchi": "+ Поставщик",
    "Narxi oshgan materiallar": "Материалы, подорожавшие у поставщиков",
    "Ta'minotchi yo'q. Kirim yozilganda ta'minotchi nomi shu ro'yxatga avtomatik qo'shiladi.": "Поставщиков нет. При записи прихода поставщик добавляется в список автоматически.",
    "{n} ta kirim · oxirgi {d}": "приходов: {n} · последний {d}",
    "bu davrda xarid yo'q": "закупок за период нет",
    "kontakt kiritilmagan": "контакты не указаны",
    "Oxirgi narx": "Последняя цена",
    "Min – max": "Мин – макс",
    "Oxirgi kirim": "Последний приход",
    "Qo'ng'iroq": "Позвонить",
    "Ro'yxatga qo'shish": "Добавить в список",
    "Summa va narxlar tanlangan davrdagi kirimlardan hisoblanadi. Narx o'zgarishi — shu ta'minotchidan oxirgi kirim narxi oldingi (boshqa) narxga nisbatan.": "Суммы и цены считаются по приходам за выбранный период. Изменение цены — последняя цена прихода от поставщика относительно предыдущей (другой) цены.",
    "Ta'minotchilar bo'yicha xaridlar": "Закупки по поставщикам",
    "Ta'minotchi": "Поставщик",
    "Oldingi narx": "Предыдущая цена",
    "O'zgarish, %": "Изменение, %",
    "Min narx": "Мин. цена",
    "Max narx": "Макс. цена",
    "Ta'minotchi ko'rsatilmagan": "Поставщик не указан",
    "Oxirgi xarid narxlari": "Последние цены закупки",
    "Omborni sanash: kamomad va ortiqcha": "Пересчёт склада: недостача и излишки",
    "Kimdan qancha olindi, narxlar qanday o'zgardi": "У кого сколько закупили, как менялись цены",
    "Sanash": "Пересчёт",
    "Ta'minot": "Снабжение",
    "Bu inventarizatsiya to'g'rilashi — uni inventarizatsiya bo'limida bekor qiling": "Это корректировка инвентаризации — отменяйте её в разделе «Инвентаризация»",
    "Inventarizatsiya sanasi noto'g'ri": "Неверная дата инвентаризации",
    "Tugallanmagan inventarizatsiya bor — avval uni tasdiqlang yoki o'chiring": "Есть незавершённая инвентаризация — сначала утвердите или удалите её",
    "Sanash uchun material yo'q": "Нет материалов для пересчёта",
    "Tasdiqlangan inventarizatsiyani o'zgartirib bo'lmaydi": "Утверждённую инвентаризацию изменить нельзя",
    "Inventarizatsiyani faqat ПТО yoki administrator tasdiqlaydi": "Инвентаризацию утверждает только ПТО или администратор",
    "Bu inventarizatsiya allaqachon tasdiqlangan": "Эта инвентаризация уже утверждена",
    "Hech bir material sanalmagan": "Ни один материал не посчитан",
    "Ortiqcha (inventarizatsiya)": "Излишек (инвентаризация)",
    "Kamomad (inventarizatsiya)": "Недостача (инвентаризация)",
    "Tasdiqlangan inventarizatsiyani faqat ПТО yoki administrator bekor qiladi": "Утверждённую инвентаризацию отменяет только ПТО или администратор",
    "Faqat o'zingiz boshlagan inventarizatsiyani o'chira olasiz": "Удалить можно только начатую вами инвентаризацию",
    "Bunday ta'minotchi allaqachon bor": "Такой поставщик уже есть",
    // --- buyurtmalar rejasi ---
    "{n} omborda": "{n} на складе",
    "muddat {d}": "срок {d}",
    "muddatsiz": "без срока",
    "Qilish kerak": "Изготовить",
    "Quvvat/kun": "Мощн./день",
    "Kerak/kun": "Нужно/день",
    "Yana {n} kunni ko'rsatish": "Показать ещё {n} дн.",
    "Buyurtmalar rejasi": "План заказов",
    "Qancha kunda tugatamiz, yangi buyurtmani olsak ulguramizmi": "За сколько дней выполним и успеем ли новый заказ",
    "Du": "Пн",
    "Se": "Вт",
    "Ch": "Ср",
    "Pa": "Чт",
    "Ju": "Пт",
    "Sh": "Сб",
    "Ya": "Вс",
    "Ulguradi": "Успевает",
    "Xavfli — zaxira yo'q": "Риск — нет запаса",
    "Kechikadi · {n} kun": "Опоздание · {n} дн.",
    "Quvvat noma'lum": "Мощность неизвестна",
    "2 yildan uzoq": "Дольше 2 лет",
    "qoliplardan": "по формам",
    "o'rtachadan": "по среднему",
    "noma'lum": "неизвестно",
    "Faol buyurtmalar": "Активные заказы",
    "Muddatida tugaydi": "Успеваем в срок",
    "Xavfli": "Под риском",
    "Kechikadi": "Опаздывают",
    "Buyurtmalar bo'yicha prognoz": "Прогноз по заказам",
    "Hisoblanmoqda…": "Расчёт…",
    "Faol buyurtma yo'q.": "Активных заказов нет.",
    "Omborda tayyor": "Готово на складе",
    "Ishlab chiqarish kerak": "Нужно изготовить",
    "Quvvat, dona/kun": "Мощность, шт/день",
    "Kerak, dona/kun": "Нужно, шт/день",
    "Tugaydi": "Завершение",
    "Cheklov: beton": "Ограничение: бетон",
    "Cheklov: qoliplar": "Ограничение: формы",
    "Quvvati noma'lum mahsulotlar (qolip soni kiritilmagan va 60 kunlik tarix yo'q): {list}. «Katalog»da qoliplar sonini kiriting.": "Изделия с неизвестной мощностью (не указано число форм и нет истории за 60 дней): {list}. Укажите число форм в «Каталоге».",
    "Kunlik ishlab chiqarish taklifi": "Предлагаемый план по дням",
    "Qaysi kuni qaysi buyurtma uchun nechta quyish kerak — eng qistovdagi buyurtma birinchi.": "Сколько и для какого заказа формовать в каждый день — самый срочный заказ первым.",
    "m³ beton": "м³ бетона",
    "Ishlab chiqarish kerak bo'lgan buyurtma yo'q.": "Нет заказов, требующих изготовления.",
    "Quvvat: qoliplar soni ÷ aylanish muddati (kun) — «Katalog»da har mahsulotga kiritiladi. Kiritilmagan bo'lsa, oxirgi 60 kundagi o'rtacha fakt olinadi. Omborda tayyor turgan mahsulot avval buyurtmalarga taqsimlanadi. Dam olish kunlari va kunlik beton cheklovi hisobga olinadi.": "Мощность: число форм ÷ оборачиваемость (дней) — задаётся для каждого изделия в «Каталоге». Если не задано, берётся средний факт за последние 60 дней. Готовая продукция на складе сначала распределяется по заказам. Учитываются выходные и дневной лимит бетона.",
    "Buyurtma qo'shildi": "Заказ добавлен",
    "Bu mahsulotning quvvati noma'lum — «Katalog»da qoliplar sonini kiriting.": "Мощность по этому изделию неизвестна — укажите число форм в «Каталоге».",
    "2 yil ichida tugatib bo'lmaydi — quvvat juda kam.": "Не выполнить и за 2 года — мощность слишком мала.",
    "Muddatga ulgurmaymiz — {n} kun kechikadi.": "В срок не успеваем — опоздание {n} дн.",
    "Ulguramiz, lekin zaxira yo'q — bir kun to'xtab qolsa kechikadi.": "Успеваем, но без запаса — один день простоя приведёт к опозданию.",
    "Omborda tayyor bor — darhol jo'natish mumkin.": "Есть на складе — можно отгружать сразу.",
    "Ulguramiz — muddatdan {n} ish kuni oldin tugaydi.": "Успеваем — завершим за {n} раб. дн. до срока.",
    "Tugash sanasi hisoblandi.": "Дата завершения рассчитана.",
    "Yangi buyurtma olsak — ulguramizmi?": "Если возьмём новый заказ — успеем?",
    "— tanlang —": "— выберите —",
    "Tugash sanasi": "Дата завершения",
    "Quvvat": "Мощность",
    "dona/kun": "шт/день",
    "Muddatga ulgurish uchun": "Чтобы успеть в срок",
    "{n} ish kuni": "{n} раб. дн.",
    "Asosiy cheklov — kunlik beton hajmi. Beton qorishni ko'paytirish yoki smena qo'shish tezlashtiradi.": "Главное ограничение — дневной объём бетона. Ускорит увеличение выпуска бетона или дополнительная смена.",
    "Asosiy cheklov — qoliplar soni. Qo'shimcha qolip yoki aylanishni tezlashtirish (bug'lash) yordam beradi.": "Главное ограничение — число форм. Помогут дополнительные формы или ускорение оборота (пропарка).",
    "Boshqa buyurtmalarga ta'siri:": "Влияние на другие заказы:",
    "muddatdan kechikadi": "опоздает к сроку",
    "Boshqa buyurtmalarni kechiktirmasdan (navbatning oxirida) bu buyurtma {d} kuni tugaydi.": "Не задерживая другие заказы (в конце очереди), этот заказ будет готов {d}.",
    "Buyurtma sifatida saqlash": "Сохранить как заказ",
    "Kamida bitta ish kuni tanlang": "Выберите хотя бы один рабочий день",
    "Rejalashtirish sozlamalari": "Настройки планирования",
    "Kuniga beton, m³": "Бетон в день, м³",
    "0 — cheklanmagan": "0 — без ограничения",
    "Ish kunlari": "Рабочие дни",
    "Dam olish / bayram kunlari": "Выходные / праздничные дни",
    "Prognoz": "Прогноз",
    "Hisoblangan sana: {d}": "Дата расчёта: {d}",
    "Quvvat asosi": "Основа мощности",
    "Boshlanadi": "Начало",
    "Kunlik taklif": "План по дням",
    "Kun": "День",
    "Buyurtma №": "Заказ №",
    "Beton kuniga, m³": "Бетон за день, м³",
    "Bu kun uchun taklif yo'q — buyurtmalar rejasida bu kunga ish chiqmagan": "На этот день предложения нет — по плану заказов работы не запланировано",
    "Reja taklifdan to'ldirildi ({n} ta mahsulot) — tekshirib, saqlang": "План заполнен из предложения ({n} изд.) — проверьте и сохраните",
    "Buyurtmalar rejasidagi taklif bo'yicha": "По предложению из плана заказов",
    "Rejani buyurtmalardan to'ldirish": "Заполнить план по заказам",
    "Qoliplar soni": "Количество форм",
    "Qolip aylanishi": "Оборот формы",
    "kun": "дн.",
    "Kunlik quvvat: {n} dona/kun — buyurtmalar rejasida ishlatiladi.": "Дневная мощность: {n} шт/день — используется в плане заказов.",
    "Dam olish kuni sanasi noto'g'ri": "Неверная дата выходного дня",
    "Muddat sanasi noto'g'ri": "Неверная дата срока",
    "Qoliplar soni manfiy bo'lmaydi": "Количество форм не может быть отрицательным",
    "Aylanish muddati kamida 0,1 kun": "Оборот — не менее 0,1 дня",
    // oylik reja (tasdiqlangan reja)
    "Kuniga o'rtacha": "В среднем за день",
    "{n} kunga reja bor": "План на {n} дн.",
    "Dastur prognozi va tasdiqlangan oylik reja (Excel / qo'lda)": "Прогноз программы и утверждённый месячный план (Excel / вручную)",
    "{n}-qatorda mahsulot tanlanmagan": "В строке {n} не выбрано изделие",
    "Dastur taklifida bu oyga ish chiqmadi — faqat buyurtmalar qo'shildi": "В предложении программы на этот месяц работ нет — добавлены только заказы",
    "Tahrirlanmoqda": "Редактируется",
    "Excel'dan yuklash": "Загрузить из Excel",
    "Oylik reja": "Месячный план",
    "Bajarildi (oy bo'yicha)": "Выполнено (за месяц)",
    "Bajarildi (kechagacha)": "Выполнено (по вчера)",
    "Bugungi reja": "План на сегодня",
    "Rejadan keyin buyurtma qoldig'i": "Остаток заказа после плана",
    "Fakt bilan solishtirish": "Сравнить с фактом",
    "bajarildi": "выполнено",
    "kam": "недовыполнено",
    "rejadan tashqari": "вне плана",
    "dam olish": "выходной",
    "{m} oyiga reja kiritilmagan.": "План на {m} не введён.",
    "{m} oyiga reja hali yo'q": "Плана на {m} пока нет",
    "Qanday boshlaymiz?": "С чего начнём?",
    "Faol buyurtmalardan qo'shish": "Добавить из активных заказов",
    "Kunlarni dastur taklifidan to'ldirish": "Заполнить дни из предложения программы",
    "— katalogdan tanlang —": "— выберите из каталога —",
    "Qoldiqni bugundan oy oxirigacha ish kunlariga teng taqsimlash": "Распределить остаток поровну по рабочим дням до конца месяца",
    "katalogda yo'q": "нет в каталоге",
    "Fakt: {n}": "Факт: {n}",
    "Buyurtmadan ortiq rejalashtirilgan": "Запланировано больше заказа",
    "varaq": "лист",
    "Qaysi oy uchun reja": "На какой месяц план",
    "qator": "строк",
    "katalog bilan bog'landi": "связано с каталогом",
    "dona rejada": "шт в плане",
    "Excel'da «{c}» ustuni bor — reja keyingi oy uchun deb taxmin qilindi. Kerak bo'lsa oyni o'zgartiring.": "В Excel есть столбец «{c}» — план определён как план на следующий месяц. При необходимости измените месяц.",
    "Excel'da {d}-kungacha ustun bor, tanlangan oyda esa {n} kun — ortiqcha kunlardagi {q} dona olinmaydi.": "В Excel столбцы до {d}-го числа, а в выбранном месяце {n} дн. — {q} шт из лишних дней не будут загружены.",
    "Bu oyga reja allaqachon bor ({n} qator) — saqlasangiz, u almashtiriladi.": "На этот месяц план уже есть ({n} строк) — при сохранении он будет заменён.",
    "Buyurtmachilar": "Заказчики",
    "Qo'shimcha ustunlar": "Доп. столбцы",
    "Excel qatori": "Строка Excel",
    "Excel'dagi nomi": "Название в Excel",
    "Katalogdagi mahsulot": "Изделие в каталоге",
    "Rejada": "В плане",
    "— bog'lanmagan (faqat nomi) —": "— без связи (только название) —",
    "Bog'lanmagan qatorlar ham saqlanadi, lekin ular uchun kunlik hisobotdagi fakt ko'rsatilmaydi va «Kunlik hisobot»ga to'ldirilmaydi.": "Строки без связи тоже сохранятся, но факт из дневного отчёта по ним не показывается и в «Дневной отчёт» они не переносятся.",
    "Tahrirlashda ochish": "Открыть для правки",
    "Ishlab chiqarish rejasi": "План производства",
    "Kunlik hisobotdagi fakt (sifatli dona)": "Факт из дневного отчёта (годные шт)",
    "Reja turi": "Вид плана",
    "Bu oy uchun tasdiqlangan reja kiritilmagan": "Утверждённый план на этот месяц не введён",
    "Tasdiqlangan rejada bu kunga ish yo'q": "В утверждённом плане на этот день работ нет",
    "Tasdiqlangan rejadagi bu kun qatorlari katalog bilan bog'lanmagan": "Строки утверждённого плана на этот день не связаны с каталогом",
    "Reja tasdiqlangan rejadan to'ldirildi ({n} ta mahsulot, {s} ta bog'lanmagan qator o'tkazib yuborildi) — tekshirib, saqlang": "План заполнен из утверждённого плана ({n} изд., пропущено строк без связи: {s}) — проверьте и сохраните",
    "Reja tasdiqlangan rejadan to'ldirildi ({n} ta mahsulot) — tekshirib, saqlang": "План заполнен из утверждённого плана ({n} изд.) — проверьте и сохраните",
    "«Buyurtmalar rejasi» → «Tasdiqlangan reja»dagi shu kun bo'yicha": "По этому дню в «План заказов» → «Утверждённый план»",
    "Tasdiqlangan rejadan to'ldirish": "Заполнить из утверждённого плана",
    "Dastur rejasi": "План программы",
    "Buyurtmalar bo'yicha avtomatik prognoz": "Автоматический прогноз по заказам",
    "Tasdiqlangan reja": "Утверждённый план",
    "Oylik reja: Excel'dan yoki qo'lda": "Месячный план: из Excel или вручную",
    "Excel'dan yuklangan": "Загружен из Excel",
    "Qo'lda tuzilgan": "Составлен вручную",
    "Dastur taklifidan tuzilgan": "Составлен из предложения программы",
    "Qo'lda tuzish": "Составить вручную",
    "Buyurtmalardan": "Из заказов",
    "Dastur taklifidan": "Из предложения программы",
    "Tasdiqlangan reja Excel faylini tanlang — mahsulotlar katalog bilan avtomatik bog'lanadi, saqlashdan oldin ko'rib chiqasiz.": "Выберите Excel-файл утверждённого плана — изделия автоматически свяжутся с каталогом, перед сохранением вы всё проверите.",
    "Bo'sh jadval: mahsulot, buyurtmachi va kunlarni o'zingiz kiritasiz. Excel'dan nusxalab qo'yish ham mumkin.": "Пустая таблица: изделия, заказчиков и дни вводите сами. Можно вставлять скопированное из Excel.",
    "Faol buyurtmalar qatorlarga qo'yiladi (buyurtmachi, soni, jo'natilgani) — kunlarni o'zingiz taqsimlaysiz.": "Активные заказы станут строками (заказчик, количество, отгружено) — дни распределяете сами.",
    "Dastur hisoblagan kunlik taklif shu oyga ko'chiriladi — keyin xohlagancha tuzatasiz.": "Дневное предложение программы переносится в этот месяц — дальше правьте как угодно.",
    "Faylni o'qib bo'lmadi": "Не удалось прочитать файл",
    "Excel'da «Наименование» ustuni topilmadi — oylik reja shaklidagi faylni tanlang": "В Excel не найден столбец «Наименование» — выберите файл в форме месячного плана",
    "Excel'da kunlar (1, 2, 3 …) ustunlari topilmadi": "В Excel не найдены столбцы дней (1, 2, 3 …)",
    "Excel'da mahsulot qatorlari topilmadi": "В Excel не найдены строки изделий",
    "Reja": "План",
    "Fakt": "Факт",
    "{n} ta yangi mahsulot qo'shildi": "Добавлено новых изделий: {n}",
    "Dastur taklifidagi kunlar shu rejaga yoziladi (bugundan boshlab, o'sha mahsulotlar ustiga). Davom etamizmi?": "Дни из предложения программы будут записаны в план (с сегодняшнего дня, поверх этих изделий). Продолжить?",
    "Bugundan boshlab": "С сегодняшнего дня",
    "Butun oy": "Весь месяц",
    "Katalog bilan bog'lanmagan mahsulotlar bor ({n} ta) — ular uchun fakt ko'rsatilmaydi. «Tahrirlash» → «Mahsulotlar bo'yicha»da katalogdan tanlang.": "Есть изделия без связи с каталогом ({n}) — факт по ним не показывается. Выберите их в каталоге: «Изменить» → «По изделиям».",
    "Olib tashlash": "Убрать",
    "Mahsulot qo'shish": "Добавить изделие",
    "+ mahsulot qo'shish": "+ добавить изделие",
    "Rejadagi mahsulotlar": "Изделия плана",
    "Katalogdan": "Из каталога",
    "Oldingi kundan": "Как вчера",
    "Taqsimlash": "Распределить",
    "Mahsulotni rejadan o'chirish": "Удалить изделие из плана",
    "Bu mahsulot butun oy rejasidan o'chiriladi. Davom etamizmi?": "Изделие будет удалено из плана на весь месяц. Продолжить?",
    "Kunlar bo'yicha reja": "План по дням",
    "Kunlik reja": "План по дням",
    "Har kunga mahsulot qo'shing va sonini yozing. «Oldingi kundan» — bir kun oldingi rejani nusxalaydi.": "Добавляйте изделия в каждый день и указывайте количество. «Как вчера» копирует план предыдущего дня.",
    "Tasdiqlangan reja kunma-kun: qaysi kuni qaysi mahsulotdan nechta. O'tgan kunlarda kunlik hisobotdagi fakt ham ko'rsatiladi.": "Утверждённый план по дням: какого изделия сколько и в какой день. Для прошедших дней показан факт из дневного отчёта.",
    "Bugundan keyin rejada ish yo'q.": "С сегодняшнего дня работ в плане нет.",
    "Rejada ish yo'q.": "В плане нет работ.",
    "Mahsulotlar bo'yicha": "По изделиям",
    "{m} oyi uchun reja saqlandi — hamma foydalanuvchilarga ko'rinadi": "План на {m} сохранён — виден всем пользователям",
    "Saqlangan rejalar:": "Сохранённые планы:",
    "O'tgan kunlar kunlik hisobotdan olindi ({n} ta yozuv)": "Прошедшие дни взяты из дневного отчёта (записей: {n})",
    "Bugundan oldingi kunlarga kunlik hisobotdagi fakt yoziladi": "В дни до сегодняшнего записывается факт из дневного отчёта",
    "O'tgan kunlarni hisobotdan olish": "Прошедшие дни — из отчёта",
    "Qopqoq: kuniga {n} ta yoki 0 («{h}» qolibida)": "Крышка: в день {n} шт или 0 (в форме «{h}»)",
    "{h} qolibida, {n} tadan": "в форме {h}, по {n} шт",
    "{n} omborga": "{n} на склад",
    "{n} / quyish": "{n} / заливка",
    "{h} qolibida": "в форме {h}",
    "Lotok qopqog'i: «{h}» qolibiga bo'lib quyiladi — kuniga yo {n} ta, yo umuman yo'q; o'sha kuni «{h}»ning bitta qolibi band bo'ladi. «Qoliplar soni» — bitta quyishdagi qopqoqlar soni.": "Крышка лотка: заливается в форму «{h}», разделённую на части — в день либо {n} шт, либо ничего; в этот день одна форма «{h}» занята. «Количество форм» — число крышек за одну заливку.",
    "rejadan tashqari: {n}": "вне плана: {n}",
    "Har katakda: mahsulot va rejadagi soni (dona); o'tgan kunlarda tagida — kunlik hisobotdagi fakt (yashil — bajarildi, qizil — kam). Pastki satr — kun bo'yicha jami va beton hajmi.": "В каждой ячейке: изделие и количество по плану (шт); для прошедших дней ниже — факт из дневного отчёта (зелёный — выполнено, красный — недовыполнено). Нижняя строка — итог за день и объём бетона.",
    "Bugundan oy oxirigacha": "С сегодняшнего дня до конца месяца",
    "Kamida bitta mahsulot va sonini kiriting": "Укажите хотя бы одно изделие и количество",
    "{d} kungi jo'natish": "Отгрузка за {d}",
    "Qaysi jo'natish (mashina)": "Какая отгрузка (машина)",
    "mashinasiz": "без машины",
    "Qator": "Строка",
    "Summani yozish (buyurtmadagi narx, bo'lmasa kalkulyatsiyadagi QQS bilan narx)": "Указывать сумму (цена из заказа, иначе цена с НДС из калькуляции)",
    "Imzo": "Подпись",
    "imzosiz": "без подписи",
    "Imzoni olib tashlash": "Убрать подпись",
    "Qayta chizish": "Перерисовать",
    "Imzo chizish": "Нарисовать подпись",
    "Nusxalar": "Экземпляры",
    "Ikkita (albom)": "Два (альбом)",
    "Bitta (A4)": "Один (A4)",
    "PDF yuklab olish": "Скачать PDF",
    "Shu yerga imzo chizing": "Распишитесь здесь",
    "Shu kungi jo'natish bo'yicha yuk xati (PDF)": "Накладная по отгрузке за этот день (PDF)",
    "tanlang yoki yozing": "выберите или введите",
    "Bu kunda jo'natish yozilmagan. «Договор №» dan shartnomani tanlang — mahsulotlar shu buyurtmadan qo'yiladi, yoki qatorlarni o'zingiz yozing.": "За этот день отгрузка не записана. Выберите договор в поле «Договор №» — изделия подставятся из этого заказа, или заполните строки вручную.",
  },

  ruPatterns: [
    [/^Bekor qilib bo'lmaydi: to'g'ri markadan keyin jo'natilgan\. Qoldiq: (.*)$/, "Нельзя отменить: с правильной марки уже отгружено. Остаток: $1"],
    [/^Bitta buyurtmada (\d+) tadan ko'p mahsulot bo'lmaydi$/, "В одном заказе не более $1 изделий"],
    [/^Omborda yetarli emas\. Qoldiq: (.*)$/, "Недостаточно на складе. Остаток: $1"],
    [/^Ko'p marta noto'g'ri parol kiritildi\. (\d+) daqiqadan keyin urinib ko'ring$/, "Слишком много неверных попыток. Повторите через $1 мин."],
    [/^Noto'g'ri qiymat: (.*)$/, "Неверное значение: $1"],
    [/^«(.+)» ro'yxat \(massiv\) bo'lishi kerak$/, "«$1» должно быть списком (массивом)"],
    [/^Xatolik \((\d+)\)$/, "Ошибка ($1)"],
    [/^Kirim: (.*)$/, "Приход: $1"],
    [/^Chiqim: (.*)$/, "Расход: $1"],
    [/^O'chirilayotgan andozaga (\d+) ta mahsulot bog'langan — avval ularni boshqa andozaga o'tkazing$/, "К удаляемому шаблону привязано изделий: $1 — сначала переведите их в другой шаблон"],
    [/^Ko'rsatkich oldingisidan kam bo'lishi mumkin emas \((.*)\)$/, "Показание не может быть меньше предыдущего ($1)"],
  ],
};
