// Tarjimalar. Kalit — o'zbekcha (lotin) matn.
//  kr — o'zbekcha (kirill): faqat avtomatik o'girish noto'g'ri chiqadigan satrlar (qolgani lib/i18n.js → toCyr)
//  ru — ruscha
//  ruPatterns — ichida o'zgaruvchan qismi bo'lgan server xabarlari

export const DICT = {
  kr: {
    Excel: "Excel",
    "Excel yuklab olish": "Excel юклаб олиш",
    "Hisobot CSV": "Ҳисобот CSV",
    "«На экран Домой» / «Add to Home Screen»": "«На экран Домой» / «Add to Home Screen»",
    "Qidirish: Ф5, лоток…": "Қидириш: Ф5, лоток…",
    "Ma'lumotlar bazasiga ulanib bo'lmadi — MONGODB_URI va Atlas Network Access (0.0.0.0/0) ni tekshiring":
      "Маълумотлар базасига уланиб бўлмади — MONGODB_URI ва Atlas Network Access (0.0.0.0/0) ни текширинг",
    "Foydalanuvchi yo'q. Birinchi kirish uchun serverda APP_PASSWORD ni o'rnating":
      "Фойдаланувчи йўқ. Биринчи кириш учун серверда APP_PASSWORD ни ўрнатинг",
    "Serverga ulanib bo'lmadi. Internet yoki NEXT_PUBLIC_API_URL ni tekshiring.":
      "Серверга уланиб бўлмади. Интернет ёки NEXT_PUBLIC_API_URL ни текширинг.",
    "Sana formati YYYY-MM-DD": "Сана формати YYYY-MM-DD",
    "from va to sanalarini YYYY-MM-DD formatida bering": "from ва to саналарини YYYY-MM-DD форматида беринг",
  },

  ru: {
    /* ---------- karkas, menyu, kirish ---------- */
    "Kunlik hisobot": "Ежедневный отчёт",
    "Reja / fakt, xomashyo sarfi, jo'natish": "План / факт, расход сырья, отгрузка",
    "Oylik hisobot": "Месячный отчёт",
    "Reja bajarilishi, haqiqiy sarf va norma farqi": "Выполнение плана, фактический расход и отклонение от нормы",
    Ombor: "Склад",
    "Materiallar qoldig'i, kirim va chiqim": "Остатки материалов, приход и расход",
    "Kirim-chiqim tarixi": "История прихода и расхода",
    "Ombordagi barcha harakatlar": "Все движения по складу",
    "Qoldiq va ehtiyoj": "Остатки и потребность",
    "Material va tayyor mahsulot qiymati, buyurtmalar uchun ehtiyoj": "Стоимость материалов и готовой продукции, потребность под заказы",
    Buyurtmalar: "Заказы",
    "Buyurtmachilar, muddatlar va jo'natish holati": "Заказчики, сроки и статус отгрузки",
    Kalkulyatsiya: "Калькуляция",
    "Tannarx va sotuv narxi — Excel tartibida": "Себестоимость и цена продажи — как в Excel",
    Katalog: "Каталог",
    "Mahsulotlar, sarf normalari va kalkulyatsiya kartalari": "Изделия, нормы расхода и калькуляционные карты",
    Materiallar: "Материалы",
    "Narxlar, beton retseptlari va sozlamalar": "Цены, рецепты бетона и настройки",
    "Sex va texnika": "Цеха и техника",
    "Chiqim manzillari: bo'limlar va mashinalar": "Куда идёт расход: подразделения и машины",
    Boshqaruv: "Управление",
    "Foydalanuvchilar, zaxira nusxa va o'zgarishlar tarixi": "Пользователи, резервная копия и история изменений",
    Kunlik: "День",
    Oylik: "Месяц",
    Tarix: "История",
    "Sex/texnika": "Цеха/техника",
    Qoldiq: "Остаток",
    Buyurtma: "Заказ",
    "Zavod ish stoli": "Рабочий стол завода",
    "Davom etish uchun login va parolni kiriting": "Введите логин и пароль, чтобы продолжить",
    Login: "Логин",
    Parol: "Пароль",
    "Tekshirilmoqda…": "Проверка…",
    Kirish: "Войти",
    "Kunlik hisobotda saqlanmagan o'zgarishlar bor. Ularni tashlab ketasizmi?": "В ежедневном отчёте есть несохранённые изменения. Отменить их?",
    "Bo'limlar": "Разделы",
    "Temir-beton zavodi": "Завод ЖБИ",
    "Menyuni yopish": "Закрыть меню",
    "Server bilan ulangan": "Связь с сервером есть",
    "Ulanishda xato": "Ошибка связи",
    "Yuklanmoqda…": "Загрузка…",
    Chiqish: "Выйти",
    Kirim: "Приход",
    Chiqim: "Расход",
    "Qayta urinish": "Повторить",
    "Ma'lumotlar yuklanmoqda…": "Загрузка данных…",
    "Davom etish uchun yangi parol o'rnating.": "Чтобы продолжить, установите новый пароль.",
    "Ma'lumotlarni yuklab bo'lmadi.": "Не удалось загрузить данные.",
    "Asosiy bo'limlar": "Основные разделы",
    "Kirim yoki chiqim": "Приход или расход",
    Menyu: "Меню",
    "Parol o'zgartirildi": "Пароль изменён",
    "Serverga ulanib bo'lmadi. Internet yoki NEXT_PUBLIC_API_URL ni tekshiring.": "Нет связи с сервером. Проверьте интернет или NEXT_PUBLIC_API_URL.",
    "Serverga ulanib bo'lmadi": "Нет связи с сервером",
    "Kirishda xatolik": "Ошибка входа",

    /* ---------- rollar ---------- */
    Administrator: "Администратор",
    "ПТО muhandisi": "Инженер ПТО",
    Omborchi: "Кладовщик",
    Rahbar: "Руководитель",
    Kurator: "Куратор",
    "Rahbar (faqat ko'rish)": "Руководитель (только просмотр)",
    "Kurator (faqat ko'rish)": "Куратор (только просмотр)",

    /* ---------- umumiy ---------- */
    Saqlash: "Сохранить",
    "Saqlanmoqda…": "Сохранение…",
    Saqlandi: "Сохранено",
    "Bekor qilish": "Отмена",
    Yopish: "Закрыть",
    "O'chirish": "Удалить",
    "O'chirildi": "Удалено",
    Tasdiqlash: "Подтвердить",
    Tahrirlash: "Изменить",
    Qidirish: "Поиск",
    "Qidirish…": "Поиск…",
    "Hech narsa topilmadi": "Ничего не найдено",
    Barchasi: "Все",
    Hammasi: "Все",
    Bugun: "Сегодня",
    Sana: "Дата",
    Izoh: "Примечание",
    Nomi: "Название",
    Birlik: "Ед.",
    Narx: "Цена",
    Narxi: "Цена",
    Summa: "Сумма",
    "Summa, so'm": "Сумма, сум",
    "so'm": "сум",
    "mln so'm": "млн сум",
    dona: "шт",
    Jami: "Итого",
    Material: "Материал",
    Mahsulot: "Изделие",
    Mahsulotlar: "Изделия",
    Soni: "Кол-во",
    Miqdor: "Количество",
    Guruh: "Группа",
    Holat: "Статус",
    Turi: "Тип",
    Qiymat: "Значение",
    "Chop etish": "Печать",
    Ulashish: "Поделиться",
    Yangi: "Новый",
    "Yuklab olish": "Скачать",
    "Tayyorlanmoqda…": "Подготовка…",
    "O'zgartirish": "Изменить",
    "— o'chirilgan —": "— удалено —",
    "o'chirilgan": "удалено",
    "Excel faylni tayyorlab bo'lmadi": "Не удалось подготовить файл Excel",
    "Fayl yuklab olindi": "Файл скачан",
    "Bu qurilmada ulashish yo'q — fayl yuklab olindi": "На этом устройстве нельзя поделиться — файл скачан",
    Saqlanmadi: "Не сохранено",
    ha: "да",
    "yo'q": "нет",
    "{n} ta": "{n} шт",
    Yozuvlar: "Записи",
    Dan: "С",
    Gacha: "По",

    /* ---------- guruhlar, holatlar, qator turlari ---------- */
    Beton: "Бетон",
    Xomashyo: "Сырьё",
    Metall: "Металл",
    "Zakladnoy detallar": "Закладные детали",
    "Yoqilg'i va moylar": "Топливо и масла",
    "Ehtiyot qismlar": "Запчасти",
    Boshqa: "Прочее",
    "Xizmat / energiya": "Услуги / энергия",
    Faol: "Активные",
    Jarayonda: "В работе",
    Tayyor: "Готов",
    Topshirildi: "Сдан",
    "so'm × m³ beton": "сум × м³ бетона",
    "so'm × kg metall": "сум × кг металла",
    "% oldingi qatordan": "% от предыдущей строки",
    "% ishlab chiqarish tannarxidan": "% от производственной себестоимости",
    "so'm (qat'iy)": "сум (фиксированно)",

    /* ---------- ombor (omborchi) ---------- */
    "Ombor qiymati": "Стоимость склада",
    "Kam qoldi / tugagan": "Мало / закончилось",
    "Material qidirish…": "Поиск материала…",
    "Yangi material": "Новый материал",
    "Kam qoldi": "Мало",
    Tugagan: "Нет в наличии",
    "Material yo'q": "Материалов нет",
    min: "мин",
    "Oxirgi harakatlar": "Последние движения",
    "Bu material bo'yicha hali kirim-chiqim yo'q": "По этому материалу ещё не было движений",
    "Material qo'shildi": "Материал добавлен",
    "Minimal qoldiq": "Минимальный остаток",
    "Kod / artikul": "Код / артикул",
    "Materialni tanlang": "Выберите материал",
    "Miqdorni to'g'ri kiriting": "Введите правильное количество",
    "Qayerga ketganini kiriting: bo'lim, texnika yoki mas'ul shaxs": "Укажите, куда выдано: подразделение, техника или ответственный",
    "Kirim saqlandi": "Приход сохранён",
    "Chiqim saqlandi": "Расход сохранён",
    "Keyin qoladi": "Останется",
    "omborda yetarli emas": "на складе недостаточно",
    "Birlik narxi": "Цена за ед.",
    "Nakladnoy raqami": "Номер накладной",
    Nakladnoy: "Накладная",
    "Yetkazib beruvchi": "Поставщик",
    "Kim qabul qildi": "Кто принял",
    "Bo'lim / sex": "Подразделение / цех",
    Texnika: "Техника",
    "Kim oldi (mas'ul shaxs)": "Кто получил (ответственный)",
    "Kirimni saqlash": "Сохранить приход",
    "Chiqimni saqlash": "Сохранить расход",
    "7 kun": "7 дней",
    "30 kun": "30 дней",
    "Shu oy": "Этот месяц",
    Davr: "Период",
    "Bu yozuv bekor qilinsinmi? Qoldiq qayta hisoblanadi.": "Отменить эту запись? Остаток будет пересчитан.",
    "Bekor qilindi": "Отменено",
    "Qayerdan / qayerga": "Откуда / куда",
    "Mas'ul shaxs": "Ответственный",
    "Kim kiritdi": "Кто внёс",
    "Kirim va chiqim": "Приход и расход",
    "Faqat kirim": "Только приход",
    "Faqat chiqim": "Только расход",
    "Barcha materiallar": "Все материалы",
    "Bo'lim / texnika": "Подразделение / техника",
    "Barcha bo'lim va texnikalar": "Все подразделения и техника",
    "Kirim summasi": "Сумма прихода",
    "Chiqim summasi": "Сумма расхода",
    "Bu davrda kirim-chiqim yo'q": "За этот период движений нет",
    "Faqat oxirgi 1000 ta yozuv ko'rsatildi — davrni qisqartiring.": "Показаны только последние 1000 записей — сократите период.",
    jami: "итого",
    "Bo'limlar va sexlar": "Подразделения и цеха",
    "Masalan: Beton sexi, Armatura sexi, Oshxona": "Например: Бетонный цех, Арматурный цех, Столовая",
    "Texnika va mashinalar": "Техника и машины",
    "Masalan: KAMAZ, Avtokran, Yuklagich": "Например: КАМАЗ, Автокран, Погрузчик",
    "«{name}» o'chirilsinmi? Tarixda ishlatilgan bo'lsa, arxivga o'tkaziladi.": "Удалить «{name}»? Если есть в истории — будет перенесено в архив.",
    "Arxivga o'tkazildi": "Перенесено в архив",
    "Chiqim qilinganda material qayerga ketganini shu ro'yxatlardan tanlaysiz.": "При расходе место назначения выбирается из этих списков.",
    "Qo'shish": "Добавить",
    "Davlat raqami": "Гос. номер",
    Kodi: "Код",
    "Hali qo'shilmagan": "Пока ничего не добавлено",
    "(arxivda)": "(в архиве)",
    Qaytarish: "Вернуть",
    "Arxivdagilarni ko'rsatish": "Показать архивные",

    /* ---------- kunlik hisobot ---------- */
    "Saqlanmagan o'zgarishlar bor. Ularni tashlab, boshqa kunga o'tasizmi?": "Есть несохранённые изменения. Перейти на другой день без сохранения?",
    "Sarf normadan to'ldirildi — tekshirib, saqlang": "Расход заполнен по норме — проверьте и сохраните",
    "{d} saqlandi": "{d} сохранено",
    "Bu sana boshlang'ich qoldiqdan oldin — qoldiqlar noma'lum, fayl tayyorlanmaydi": "Дата раньше начального остатка — остатки неизвестны, файл не формируется",
    "Diqqat: fayl saqlanmagan o'zgarishlar bilan tayyorlandi": "Внимание: файл сформирован с несохранёнными изменениями",
    "{d} kunidagi barcha yozuvlar o'chirilsinmi?": "Удалить все записи за {d}?",
    "Oldingi kun": "Предыдущий день",
    "Keyingi kun": "Следующий день",
    Saqlanmagan: "Не сохранено",
    Saqlangan: "Сохранено",
    "Excel yuklab olish": "Скачать Excel",
    "Kunni o'chirish": "Удалить день",
    "Bu sana boshlang'ich qoldiq sanasidan ({d}) oldin — qoldiqlar hisoblanmaydi.": "Эта дата раньше даты начального остатка ({d}) — остатки не считаются.",
    "Mahsulotlar: reja / fakt": "Изделия: план / факт",
    "Reja, dona": "План, шт",
    "Fakt, dona": "Факт, шт",
    Bajarilishi: "Выполнение",
    "— mahsulot tanlang —": "— выберите изделие —",
    Reja: "План",
    Fakt: "Факт",
    reja: "план",
    fakt: "факт",
    "Qatorni o'chirish": "Удалить строку",
    "+ Mahsulot qo'shish": "+ Добавить изделие",
    "Xomashyo va materiallar": "Сырьё и материалы",
    "Sarfni normadan to'ldirish": "Заполнить расход по норме",
    "Kun boshida": "На начало дня",
    "Kerak (reja)": "Нужно (план)",
    "Norma (fakt)": "Норма (факт)",
    Sarf: "Расход (пр-во)",
    "Harakat yo'q. «Barcha materiallar»ni yoqing.": "Движений нет. Включите «Все материалы».",
    "Normadan farq: {p} %": "Отклонение от нормы: {p} %",
    "Metall kg da. «Norma (fakt)» — fakt × Норма (beton → qum/sement/sheben, elektrod = metallning {p} %). Sarf normadan 10 % dan ko'p farq qilsa sariq bilan belgilanadi. Kirim va chiqim — omborchi kiritgan harakatlar («Ombor» bo'limi).":
      "Металл в кг. «Норма (факт)» — факт × Норма (бетон → песок/цемент/щебень, электрод = {p} % от металла). Отклонение расхода от нормы более 10 % выделяется жёлтым. Приход и расход — движения, внесённые кладовщиком (раздел «Склад»).",
    "Tayyor mahsulot qoldig'i": "Остаток готовой продукции",
    "Qoldiq yo'q.": "Остатков нет.",
    Boshida: "На начало",
    Ishlandi: "Изготовлено",
    "Jo'natildi": "Отгружено",
    "Jo'natish (отгрузка)": "Отгрузка",
    Qayerga: "Куда",
    Mashina: "Машина",
    "Jo'natish yo'q.": "Отгрузок нет.",
    Samarqand: "Самарканд",
    "Mashina raqami": "Номер машины",
    "+ Jo'natish qo'shish": "+ Добавить отгрузку",

    /* ---------- oylik hisobot ---------- */
    "Kunlik beton hajmi: reja va fakt": "Суточный объём бетона: план и факт",
    "{d}-kun: fakt {f} m³, reja {p} m³": "{d}-е число: факт {f} м³, план {p} м³",
    "Bu oyda kunlik hisobot yo'q": "В этом месяце нет ежедневных отчётов",
    "{d} dan keyin bu oyda kunlik hisobot yo'q": "После {d} в этом месяце нет ежедневных отчётов",
    Oy: "Месяц",
    "Oylik Excel (har kun alohida varaq)": "Месячный Excel (каждый день — отдельный лист)",
    "Hisobot CSV": "Отчёт CSV",
    "Kunlik beton hajmi, m³": "Суточный объём бетона, м³",
    "Mahsulotlar bo'yicha": "По изделиям",
    "Bu oyda yozuv yo'q.": "В этом месяце записей нет.",
    "Materiallar: haqiqiy sarf va norma": "Материалы: фактический расход и норма",
    "Oy boshida": "На начало месяца",
    "{m} — sarf": "{m} — расход",
    "m³": "м³",
    "Sarf (haqiqiy)": "Расход (факт)",
    "Sarf (norma)": "Расход (норма)",
    Farq: "Отклонение",
    "Oy oxirida": "На конец месяца",
    "Sarf qiymati, so'm": "Стоимость расхода, сум",
    "Sarflangan materiallar qiymati": "Стоимость израсходованных материалов",
    "«Farq» — haqiqiy sarf minus norma bo'yicha sarf. 10 % dan ortiq farq sariq bilan ajratilgan.": "«Отклонение» — фактический расход минус расход по норме. Отклонение более 10 % выделено жёлтым.",
    "Ishlab chiqarildi": "Произведено",
    "Reja bajarilishi": "Выполнение плана",
    "Beton (fakt)": "Бетон (факт)",

    /* ---------- qoldiq va ehtiyoj ---------- */
    "Boshlang'ich qoldiq saqlandi": "Начальный остаток сохранён",
    "Boshlang'ich qoldiq": "Начальный остаток",
    "Omborni hisoblash shu sananing BOSHIDAGI qoldiqdan boshlanadi. Undan oldingi kunlik hisobotlar hisobga olinmaydi.": "Учёт склада начинается с остатка НА НАЧАЛО этой даты. Более ранние ежедневные отчёты не учитываются.",
    "Tayyor mahsulot, dona": "Готовая продукция, шт",
    "Qoldiq {a} boshidagi boshlang'ich qoldiq + {b} oxirigacha barcha kunlik hisobotlar va ombor harakatlaridan hisoblandi.": "Остаток рассчитан: начальный остаток на {a} + все ежедневные отчёты и движения склада по {b} включительно.",
    "Boshlang'ich qoldiq kiritilmagan — hisob noldan boshlanadi.": "Начальный остаток не введён — учёт начинается с нуля.",
    "Materiallar qiymati": "Стоимость материалов",
    "Tayyor mahsulot": "Готовая продукция",
    "Tayyor mahsulot qiymati": "Стоимость готовой продукции",
    "Materiallar qoldig'i": "Остатки материалов",
    "Barcha guruhlar": "Все группы",
    "Qiymat, so'm": "Стоимость, сум",
    "Qoldiq, dona": "Остаток, шт",
    "Narx (QQS bilan)": "Цена (с НДС)",
    "Faol buyurtmalar uchun material ehtiyoji": "Потребность в материалах под активные заказы",
    "Faol buyurtmalarda qoldiq yo'q.": "По активным заказам остатка нет.",
    "Buyurtma qoldig'i (jo'natilmagan) minus ombordagi tayyor mahsulot =": "Остаток по заказам (не отгружено) минус готовая продукция на складе =",
    "hammasi omborda bor": "всё есть на складе",
    Kerak: "Нужно",
    Omborda: "На складе",
    Yetishmaydi: "Не хватает",
    "yetadi": "хватает",
    "holatiga": "на дату",

    /* ---------- buyurtmalar ---------- */
    "Avval «Katalog»ga mahsulot qo'shing": "Сначала добавьте изделие в «Каталог»",
    "Buyurtma №{n}": "Заказ №{n}",
    "Yangi buyurtma": "Новый заказ",
    Buyurtmachi: "Заказчик",
    "so'm/dona QQS bilan, 0 = kalkulyatsiyadan": "сум/шт с НДС, 0 = из калькуляции",
    "Qabul sanasi": "Дата приёма",
    Muddat: "Срок",
    "+ Yangi buyurtma": "+ Новый заказ",
    "Bu filtr bo'yicha buyurtma yo'q.": "По этому фильтру заказов нет.",
    " · kechikdi": " · просрочен",
    "Jami ({n} ta)": "Итого ({n} шт)",
    "«Jo'natildi» ustuni kunlik hisobotdagi shu buyurtmaga bog'langan jo'natishlardan hisoblanadi. Narx 0 bo'lsa, kalkulyatsiyadagi QQS bilan narx olinadi.": "Столбец «Отгружено» считается по отгрузкам в ежедневном отчёте, привязанным к заказу. Если цена 0, берётся цена с НДС из калькуляции.",
    "№": "№",
    Qoldi: "Осталось",

    /* ---------- kalkulyatsiya, katalog, mahsulot ---------- */
    "Mahsulotlar katalogi": "Каталог изделий",
    Marka: "Марка",
    "Beton, m³": "Бетон, м³",
    "Metall, kg": "Металл, кг",
    "Og'irligi, t": "Вес, т",
    "Og'irlik taxminan: beton hajmi × 2,5 t/m³ + metall.": "Вес приблизительно: объём бетона × 2,5 т/м³ + металл.",
    Norma: "Норма",
    Tannarx: "Себестоимость",
    "Narx QQS bilan": "Цена с НДС",
    "Kalkulyatsiya kiritilmagan. «Tahrirlash» orqali materiallarni qo'shing.": "Калькуляция не заполнена. Добавьте материалы через «Изменить».",
    "Excel faylidagi narx: {p} so'm — farq {d} so'm": "Цена в файле Excel: {p} сум — разница {d} сум",
    "Excel faylidagi narx: {p} so'm — mos.": "Цена в файле Excel: {p} сум — совпадает.",
    "Qator turlari:": "Типы строк:",
    "Qidirish: Ф5, лоток…": "Поиск: Ф5, лоток…",
    "Другие затраты, jami": "Другие затраты, итого",
    "Итого (tannarx)": "Итого (себестоимость)",
    "Hisoblash turi": "Способ расчёта",
    "Marka kiritilmagan": "Не указана марка",
    "{c} — tahrirlash": "{c} — изменение",
    "Yangi mahsulot": "Новое изделие",
    "Sarf normasi (Норма)": "Норма расхода",
    "Kalkulyatsiya ·": "Калькуляция ·",
    "1 dona uchun sarf": "Расход на 1 шт",
    "+ Material": "+ Материал",
    "+ Qator": "+ Строка",
    "Avtomatik qo'shiladi": "Добавляется автоматически",
    "Beton yoki metall qo'shilganda bu yerda qum, sement, sheben va elektrod chiqadi.": "При добавлении бетона или металла здесь появятся песок, цемент, щебень и электрод.",
    "Qum, sement, sheben — beton markasi koeffitsiyentlaridan («Materiallar» bo'limi). Elektrod — metall og'irligining": "Песок, цемент, щебень — по коэффициентам марки бетона (раздел «Материалы»). Электрод — от веса металла:",
    "Sarf normasidan nusxa olish": "Скопировать из нормы расхода",
    "Metall og'irligi": "Вес металла",
    "(kg, «Логистика метала» uchun)": "(кг, для «Логистика метала»)",
    Hisoblash: "Расчёт",
    "Tannarx:": "Себестоимость:",
    "Narx QQSsiz:": "Цена без НДС:",
    "Narx QQS bilan:": "Цена с НДС:",

    /* ---------- materiallar ---------- */
    "— material —": "— материал —",
    "(so'm /": "(сум /",
    "Omborda hisobga olinadi": "Учитывается на складе",
    "Elektrod normasi shu metalldan hisoblanadi": "Норма электрода считается от этого металла",
    "Bu material — elektrod (norma metall og'irligidan avtomatik)": "Этот материал — электрод (норма автоматически от веса металла)",
    "1 m³ narxi uchun tarkib (kalkulyatsiya)": "Состав для цены 1 м³ (калькуляция)",
    "1 m³ narxi:": "Цена 1 м³:",
    "1 m³ uchun ombordan yoziladi (Норма)": "Списывается со склада на 1 м³ (Норма)",
    "Kunlik hisobotdagi «Norma» ustuni va material ehtiyoji shu koeffitsiyentlar bilan hisoblanadi.": "Столбец «Норма» в ежедневном отчёте и потребность в материалах считаются по этим коэффициентам.",
    "Sozlamalar saqlandi": "Настройки сохранены",
    "Materiallar va narxlar": "Материалы и цены",
    "+ Material qo'shish": "+ Добавить материал",
    "Narx, so'm": "Цена, сум",
    "narx yo'q": "нет цены",
    retseptdan: "по рецепту",
    "Elektrod normasi": "Норма электрода",
    "(% metall og'irligidan)": "(% от веса металла)",
    "Korxona nomi (chop etishda)": "Название предприятия (для печати)",
    "Imzo qo'yuvchilar (har biri yangi qatorda)": "Подписанты (каждый с новой строки)",
    "Sozlamalarni saqlash": "Сохранить настройки",
    Sozlamalar: "Настройки",
    "Material saqlandi": "Материал сохранён",

    /* ---------- boshqaruv ---------- */
    "Ishlab chiqarish": "Производство",
    "Jo'natish": "Отгрузка",
    "omborda hisoblanadi": "учитывается на складе",
    "elektrod asosi": "база электрода",
    "retsept (1 m³)": "рецепт (1 м³)",
    "Sarf normasi": "Норма расхода",
    "metall, kg": "металл, кг",
    "ishlab chiqarish xarajatlari": "производственные затраты",
    "boshqa xarajatlar": "прочие затраты",
    "marja, %": "маржа, %",
    "QQS, %": "НДС, %",
    "elektrod, %": "электрод, %",
    "parolni almashtirishi kerak": "должен сменить пароль",
    "kalkulyatsiya andozasi": "шаблон калькуляции",
    "minimal qoldiq": "минимальный остаток",
    "bo'lim / sex": "подразделение / цех",
    "mas'ul shaxs": "ответственный",
    "yetkazib beruvchi": "поставщик",
    reja_: "план",
    izoh: "примечание",
    sarf: "расход",
    kirim: "приход",
    soni: "кол-во",
    buyurtmachi: "заказчик",
    mashina: "машина",
    buyurtma: "заказ",
    mahsulot: "изделие",
    material: "материал",
    nomi: "название",
    birlik: "ед.",
    guruh: "группа",
    narx: "цена",
    elektrod: "электрод",
    norma: "норма",
    marka: "марка",
    materiallar: "материалы",
    holat: "статус",
    muddat: "срок",
    sana: "дата",
    korxona: "предприятие",
    imzolar: "подписи",
    rol: "роль",
    faol: "активен",
    login: "логин",
    parol: "пароль",
    qiymat: "значение",
    turi: "тип",
    tartib: "порядок",
    izohlar: "примечания",
    arxivda: "в архиве",
    texnika: "техника",
    nakladnoy: "накладная",
    Foydalanuvchi: "Пользователь",
    "Zaxira nusxa": "Резервная копия",
    "Ombor harakati": "Движение склада",
    "Sex / texnika": "Цех / техника",
    "Qo'shildi": "Добавлено",
    "O'zgardi": "Изменено",
    Kirdi: "Вход",
    "Yuklab olindi": "Скачано",
    "{n}-qator": "строка {n}",
    "Foydalanuvchi: {u}": "Пользователь: {u}",
    "Yangi foydalanuvchi": "Новый пользователь",
    "Ism familiya": "Имя и фамилия",
    Rol: "Роль",
    "lotin harflari": "латинскими буквами",
    "Vaqtinchalik parol": "Временный пароль",
    "kamida 6 belgi": "не менее 6 символов",
    "Foydalanuvchi qo'shildi — birinchi kirishda parolini o'zgartiradi": "Пользователь добавлен — при первом входе сменит пароль",
    "{u} — yangi parol": "{u} — новый пароль",
    "Yangi vaqtinchalik parol": "Новый временный пароль",
    "Parolni o'rnatish": "Установить пароль",
    "Parol o'rnatildi. Foydalanuvchi keyingi kirishda uni o'zgartiradi": "Пароль установлен. Пользователь сменит его при следующем входе",
    Foydalanuvchilar: "Пользователи",
    "Foydalanuvchi qo'shish": "Добавить пользователя",
    Ism: "Имя",
    "Oxirgi kirish": "Последний вход",
    "bu siz": "это вы",
    "O'chirilgan": "Отключён",
    Bloklash: "Заблокировать",
    Faollashtirish: "Включить",
    "hamma narsani va foydalanuvchilarni boshqaradi.": "управляет всем, включая пользователей.",
    "hisobot, ombor, buyurtma, katalog va materiallarni tahrirlaydi.": "редактирует отчёты, склад, заказы, каталог и материалы.",
    "ombor kirim-chiqimini, sex va texnikani yuritadi.": "ведёт приход и расход склада, цеха и технику.",
    "va": "и",
    "hamma bo'limni ko'radi, lekin hech narsani o'zgartira olmaydi. Bloklangan foydalanuvchi darhol tizimdan chiqariladi.": "видят все разделы, но ничего не могут менять. Заблокированный пользователь сразу выходит из системы.",
    "O'zgarishlar tarixi": "История изменений",
    "Bo'lim": "Раздел",
    "Barcha bo'limlar": "Все разделы",
    "Barcha foydalanuvchilar": "Все пользователи",
    "Hozircha yozuv yo'q.": "Записей пока нет.",
    Vaqt: "Время",
    Kim: "Кто",
    Amal: "Действие",
    Nima: "Что",
    Farqlar: "Изменения",
    yopish: "скрыть",
    "… yana {n} ta o'zgarish": "… ещё {n} изменений",
    "Yana ko'rsatish": "Показать ещё",
    "Qatorni bosing — nima, qaysi qiymatdan qaysi qiymatga o'zgargani ko'rinadi. Yozuvlar 13 oy saqlanadi.": "Нажмите на строку — увидите, что и с какого значения на какое изменилось. Записи хранятся 13 месяцев.",
    "{f} yuklab olindi": "{f} скачан",
    "Butun bazani bitta faylga yuklab olish": "Скачать всю базу одним файлом",
    "Materiallar, mahsulotlar, barcha kunlik hisobotlar, buyurtmalar va sozlamalar. Parollar faylga yozilmaydi.": "Материалы, изделия, все ежедневные отчёты, заказы, склад и настройки. Пароли в файл не попадают.",
    "Hali birorta ham zaxira nusxa olinmagan.": "Резервных копий ещё не было.",
    "Oxirgi nusxa: {d} ({u})": "Последняя копия: {d} ({u})",
    " — {n} kun oldin, yangisini oling": " — {n} дн. назад, сделайте новую",
    "Zaxiradan qanday tiklanadi?": "Как восстановить из копии?",
    "Faylni kompyuterdagi": "Скопируйте файл в папку",
    "papkasiga nusxalang.": "на компьютере.",
    "Avval tekshiring (hech narsa o'zgarmaydi):": "Сначала проверьте (ничего не изменится):",
    "Tiklash:": "Восстановить:",
    "Tiklashda bazadagi hozirgi ma'lumotlar zaxiradagisi bilan almashtiriladi. Foydalanuvchilar tegilmaydi.": "При восстановлении текущие данные заменяются данными из копии. Пользователи не затрагиваются.",

    /* ---------- parol, o'rnatish ---------- */
    "Yangi parollar bir xil emas": "Новые пароли не совпадают",
    "Yangi parol o'rnating": "Установите новый пароль",
    "Parolni o'zgartirish": "Смена пароля",
    "Siz vaqtinchalik parol bilan kirdingiz. Davom etish uchun o'zingizning parolingizni o'rnating.": "Вы вошли с временным паролем. Чтобы продолжить, установите свой пароль.",
    "Joriy parol": "Текущий пароль",
    "Yangi parol": "Новый пароль",
    "(kamida 6 belgi)": "(не менее 6 символов)",
    "Yangi parol (yana bir marta)": "Новый пароль (ещё раз)",
    "Telefonga ilova qilib o'rnating": "Установите как приложение на телефон",
    "Safari pastidagi": "Нажмите внизу Safari кнопку",
    "tugmasini bosing, so'ng": ", затем выберите",
    "ni tanlang.": ".",
    "Bosh ekranda ikonka paydo bo'ladi va ilova brauzersiz ochiladi.": "На главном экране появится значок, и приложение будет открываться без браузера.",
    "O'rnatish": "Установить",

    /* ---------- Excel eksport ---------- */
    "Narxlar ro'yxati": "Прайс-лист",
    "Narxlar ro'yxati (Excel)": "Прайс-лист (Excel)",
    "Mahsulotlar narxlari (kalkulyatsiya bo'yicha)": "Цены изделий (по калькуляции)",
    "Narx QQSsiz": "Цена без НДС",
    "Narx bo'sh bo'lsa — kalkulyatsiya kiritilmagan.": "Пустая цена — калькуляция не заполнена.",
    "Excel faylni yuklab olish": "Скачать файл Excel",
    "Telegram, pochta va boshqalarga yuborish": "Отправить в Telegram, по почте и т.д.",
    "Oylik xulosa (Excel)": "Итоги месяца (Excel)",
    "Xulosani ulashish": "Поделиться итогами",
    "Oylik hisobot — {p}: mahsulotlar": "Месячный отчёт — {p}: изделия",
    "Oylik hisobot — {p}: materiallar": "Месячный отчёт — {p}: материалы",
    "Ishlab chiqarildi: {f} dona, reja bajarilishi {r} %, beton {b} m³, jo'natildi {s} dona": "Произведено: {f} шт, выполнение плана {r} %, бетон {b} м³, отгружено {s} шт",
    "Kirim-chiqim": "Приход-расход",
    "Material bo'yicha": "По материалам",
    "Material bo'yicha jami": "Итого по материалам",
    "Materiallar qoldig'i — {d} holatiga": "Остатки материалов на {d}",
    "Tayyor mahsulot qoldig'i — {d} holatiga": "Остатки готовой продукции на {d}",
    Ehtiyoj: "Потребность",
    "Ombor qoldig'i": "Остатки склада",
    "Ombor qoldig'i — {d} holatiga": "Остатки склада на {d}",
    Tayyorlandi: "Сформировано",
    "Ma'lumot yo'q": "Нет данных",
    /* ---------- metr → kg ---------- */
    metr: "метр",
    m: "м",
    "kg/m": "кг/м",
    avtomatik: "автоматически",
    birlik: "ед.",
    "ПТО kiritgan koeffitsiyent": "Коэффициент задан ПТО",
    "1 metr og'irligi": "Вес 1 метра",
    "kg/m — omborchi metrda yozsa": "кг/м — если кладовщик вводит в метрах",
    "Bo'sh qoldirilsa — avtomatik": "Если пусто — автоматически",
    "Metrdan aylantirish kerak bo'lsa, kiriting": "Заполните, если нужен пересчёт из метров",
    Metrda: "В метрах",
    "Bu material uchun metrdan aylantirish koeffitsiyenti yo'q": "Для этого материала нет коэффициента пересчёта из метров",
    /* ---------- server xabarlari ---------- */
    "Login yoki parol noto'g'ri": "Неверный логин или пароль",
    "Login va parolni kiriting": "Введите логин и пароль",
    "Foydalanuvchi yo'q. Birinchi kirish uchun serverda APP_PASSWORD ni o'rnating": "Пользователей нет. Для первого входа задайте APP_PASSWORD на сервере",
    "Qaytadan kiring": "Войдите заново",
    "Avval o'zingizning parolingizni o'rnating": "Сначала установите свой пароль",
    "Sizda bu amal uchun ruxsat yo'q": "У вас нет прав на это действие",
    "Bu bo'lim faqat administrator uchun": "Этот раздел только для администратора",
    "Yozuv topilmadi": "Запись не найдена",
    "Joriy parol noto'g'ri": "Неверный текущий пароль",
    "Yangi parol eskisidan farq qilsin": "Новый пароль должен отличаться от старого",
    "Parol kamida 6 belgidan iborat bo'lsin": "Пароль — не менее 6 символов",
    "Parol juda uzun": "Пароль слишком длинный",
    "Rol noto'g'ri": "Неверная роль",
    "Kamida bitta faol administrator qolishi kerak": "Должен остаться хотя бы один активный администратор",
    "O'zingizni o'chira olmaysiz": "Нельзя удалить самого себя",
    "Material normalarda, retseptda, kunlik hisobotda yoki ombor tarixida ishlatilgan — o'chirib bo'lmaydi. Uni arxivga o'tkazing.": "Материал используется в нормах, рецептах, ежедневных отчётах или истории склада — удалить нельзя. Переведите его в архив.",
    "Mahsulot buyurtma yoki kunlik hisobotda ishlatilgan — o'chirib bo'lmaydi": "Изделие используется в заказах или ежедневных отчётах — удалить нельзя",
    "Sana formati YYYY-MM-DD": "Формат даты ГГГГ-ММ-ДД",
    "from va to sanalarini YYYY-MM-DD formatida bering": "Укажите даты from и to в формате ГГГГ-ММ-ДД",
    "Harakat turi noto'g'ri (kirim yoki chiqim)": "Неверный тип движения (приход или расход)",
    "Material topilmadi": "Материал не найден",
    "Bu material omborda hisobga olinmaydi": "Этот материал не учитывается на складе",
    "Bo'lim topilmadi": "Подразделение не найдено",
    "Texnika topilmadi": "Техника не найдена",
    "Faqat o'zingiz kiritgan yozuvni 24 soat ichida bekor qila olasiz": "Отменить можно только свою запись и только в течение 24 часов",
    "Bu kirimdan keyin material ishlatilgan — bekor qilsangiz qoldiq manfiy bo'lib qoladi": "После этого прихода материал уже расходовался — при отмене остаток станет отрицательным",
    "Mahsulot topilmadi": "Изделие не найдено",
    "Kalkulyatsiya andozasi noto'g'ri": "Неверный шаблон калькуляции",
    "Boshlang'ich qoldiq sanasi noto'g'ri": "Неверная дата начального остатка",
    "Bunday API yo'li yo'q": "Такого адреса API нет",
    "Bunday yozuv allaqachon bor": "Такая запись уже есть",
    "JSON noto'g'ri": "Неверный JSON",
    "Serverda xatolik": "Ошибка на сервере",
    "Ma'lumotlar bazasiga ulanib bo'lmadi — MONGODB_URI va Atlas Network Access (0.0.0.0/0) ni tekshiring": "Нет связи с базой данных — проверьте MONGODB_URI и Atlas Network Access (0.0.0.0/0)",
    "Material normalarda, retseptda yoki kunlik hisobotda ishlatilgan — o'chirib bo'lmaydi": "Материал используется — удалить нельзя",
    "Buyurtmachi kiritilmagan": "Не указан заказчик",
    "Login faqat lotin harflari, raqam, nuqta, _ va - dan iborat bo'lsin": "Логин — только латинские буквы, цифры, точка, _ и -",
    "Login kamida 3 belgi": "Логин — не менее 3 символов",
    "Login kiritilmagan": "Не указан логин",
    "Manfiy son kiritib bo'lmaydi": "Отрицательное число недопустимо",
    "Miqdor 0 dan katta bo'lishi kerak": "Количество должно быть больше 0",
    "Nomi kiritilmagan": "Не указано название",
    "Soni kamida 1": "Количество — не менее 1",
    "Soni kamida 1 bo'lishi kerak": "Количество должно быть не менее 1",
  },

  ruPatterns: [
    [/^Omborda yetarli emas\. Qoldiq: (.*)$/, "Недостаточно на складе. Остаток: $1"],
    [/^Ko'p marta noto'g'ri parol kiritildi\. (\d+) daqiqadan keyin urinib ko'ring$/, "Слишком много неверных попыток. Повторите через $1 мин."],
    [/^Noto'g'ri qiymat: (.*)$/, "Неверное значение: $1"],
    [/^«(.+)» ro'yxat \(massiv\) bo'lishi kerak$/, "«$1» должно быть списком (массивом)"],
    [/^Xatolik \((\d+)\)$/, "Ошибка ($1)"],
    [/^Kirim: (.*)$/, "Приход: $1"],
    [/^Chiqim: (.*)$/, "Расход: $1"],
  ],
};
